"""
@BY: Reem Alghamdi
@DATE: 31-10-2020
"""
from copy import deepcopy

from ch1.code.ch1_08 import hamming_distance
from ch3.code.ch3_08 import format_adjacency_list
import pandas as pd
import numpy as np

from ch8.code.ch8_extra import Tree, Node


alphabet = ["A", "C", "G", "T"]


def small_parsimony(t):
    """
    given a tree where the leaves are ONE character from each original tree

    """
    visited = []
    s = {}
    for v in t.nodes:
        if len(t.edges[v]) == 1:
            visited.append(v)
            s[v] = {}
            for k in alphabet:
                if v.label == k:
                    s[v][k] = 0
                else:
                    s[v][k] = float("inf")
            v.s = s[v]
            v.b = []
    while len(visited) < len(t.nodes):
        for v in [x for x in t.nodes if x not in visited][:]:
            children = []
            for edge in t.edges[v]:
                node = edge[0]
                if node in visited:
                    children.append(node)
            if len(children) < 2:
                continue
            visited.append(v)
            s[v] = {}
            mins = []
            min_score = float("inf")
            for k in alphabet:
                score = 0
                for node in children:
                    minimum = float("inf")
                    for i in alphabet:
                        if s[node][i] + int(i != k) < minimum:
                            minimum = s[node][i] + int(i != k)
                    score += minimum
                if score < min_score:
                    min_score = score
                    mins = [k]
                elif score == min_score:
                    mins.append(k)
                s[v][k] = score
            v.add_s(s[v])
            v.add_b(mins)
            # print(v.b)
            if len(v.b) == 1:
                v.label = v.b[0]
                if len(t.edges[t.root]) != 2 and len(t.edges[t.root]) < len(t.edges[v]):
                    t.root = v

    t.root.label = min(t.root.s, key=t.root.s.get)
    for child in t.edges[t.root]:
        backtrack(t, [t.root], t.root, child[0])

    return t


def backtrack(t, visited, current, next_node):
    if next_node not in visited:
        visited.append(next_node)
        if not next_node.label:
            if current.label in next_node.b:
                next_node.label = current.label
            else:
                min_letter = None
                minimum = float("inf")
                for c in next_node.b:
                    if current.s[c] < minimum:
                        min_letter = c
                        minimum = current.s[c]
                next_node.label = min_letter

        for n in t.edges[next_node]:
            backtrack(t, visited, next_node, n[0])


def solve_small_parsimony(n, string):

    tree = Tree()
    nodes = {}
    for i, line in enumerate(string.split("\n")):
        pairs = line.split("->")
        a = pairs[0]
        b = pairs[1]
        if a.isnumeric():
            if a in nodes:
                a = nodes[a]
            else:
                a = Node(a)
                nodes[pairs[0]] = a
        else:
            a = Node(i, a)

        if b.isnumeric():
            if b in nodes:
                b = nodes[b]
            else:
                b = Node(b)
                nodes[pairs[1]] = b
        else:
            b = Node(i, b)

        tree.link(a, b)

    tree.make_root()
    # print("ROOT", tree.root)
    tree.AdjList(is_string=True)


    o = small_parsimony(tree)
    for node in o.nodes:
        print(node.label, node.index, node.s, node.b)


def solve_full_tree(t):
    m = 0
    tree = Tree()
    nodes = {}
    for i, line in enumerate(string.split("\n")):
        pairs = line.split("->")
        a = pairs[0]
        b = pairs[1]
        if a.isnumeric():
            if a in nodes:
                a = nodes[a]
            else:
                a = Node(a)
                nodes[pairs[0]] = a
        else:
            if m == 0:
                m = len(a)
            a = Node(i, a)

        if b.isnumeric():
            if b in nodes:
                b = nodes[b]
            else:
                b = Node(b)
                nodes[pairs[1]] = b
        else:
            if m == 0:
                m = len(b)
            b = Node(i, b)

        tree.link(a, b)
    tree.make_root()
    # tree.AdjList(is_string=True)

    sub_trees = []
    # print(m)
    for i in range(m):
        sub_trees.append(deepcopy(tree))
        for node in sub_trees[-1].nodes:
            if node.label:
                node.label = node.label[i]
        # sub_trees[-1].make_root()
        small_parsimony(sub_trees[-1])
        # print("ROOT", sub_trees[-1].root)
        # sub_trees[-1].AdjList(is_string=True)
        # print()

    final_tree = deepcopy(tree)
    for node in final_tree.nodes:
        node.label = ""
        for i in range(m):
            # print(sub_trees[i].nodes)
            node.label += [x for x in sub_trees[i].nodes if x.index == node.index][0].label

    total = 0
    for start, w_edges in final_tree.edges.items():
        for edge in w_edges:
            end, weight = edge
            edge[1] = hamming_distance(start.label, end.label)
            total += edge[1]
        # print(start, w_edges)
    print(total // 2)
    final_tree.AdjList(is_string=True)


if __name__ == "__main__":
#     string = """4->CAAATCCC
# 4->ATTGCGAC
# 5->CTGCGCTG
# 5->ATGGACGA
# 6->4
# 6->5"""
#     solve_full_tree(string)
    string ="""128->CGCCTGAACTATGAATAGACCTGGGACAATGAGTCAGAGGAAATCTATCATTGAGAGATCCCGCGTCGCCTCTGTCCCGAAGGGCCCCAGCTTACAGCCCGTGATGAGGAAGTAGTCACTTGTTAGCATGATCTTGTCGAGTTACTAGCAAGGCTATCCTC
128->CCATCTCGTTCTGCCTACCGTCCCCTATAGTGAGGCCCGGGCTCCAGGCCGGACCCATGATGCGCGCTCGACAATACAACGCCTATCACGAACAGTAGACCTTAAAGCTTTAGTGAGTGTTCGCGGTGGGTTAAGGAAGGATTTTGCGCTAGATGGAGCTT
129->GGCCCGCTTATCCGTAACGGATCAAAGGATTCCCTATGATACCTCAGAGACTCACGTGATTGGAAAGTATTCCCAGCTTTGGTTTTTTGCCCTGATTGATAAGGCACCAGCTGTAGGCCAGATTCACACCGCCAAAAACGTTTTACTGCCGTACAAATTGA
129->GTACATGCGCCACCTTGCGCACGCAATGAGTTACAGAGGCATCCGGCTGAGCTCTTACTTTCGGGTTGACAAACGAGAATGCAACGCAGCCAGTGCCGAAATTGCCCAGCCTCGTCATAAGCGGATTAAGAGAGAGTCCTCGTAGGTGGGAGACGGGCGTG
130->GATGGATGGCGAAACGGTTGTGCTCTCTGTAACTACCGCGTCTCAATCCTAATCCAAGGATCACCGTCGTGAGGCTCTTACGTCCAAGTCCAGCGACCCTTTATTAACCCTCGGCAGCCTGAAAACGTCGCGCGTTTGGCCGTCCGGAAGATGAACCGATC
130->GGCCATTTTAATATTGGCTCGGCCCTGGGTGCCCCTCAGCTAACCGTTTTCGACCGTCAAGGTGGGCCCGGCCACGGGAATGGAGCAGGGGTGTGCGGCTTGCCTAATCAGTACATGGGGTTACTAACCGGTTATGGGTACTCTGAAATACTTAGTGGACG
131->GGTGGACTTTTACGCGTCGGGTAGGCGGCATAATGCTGGAATGCTTGAGGGCAACCGTGACGGGGAGTAACGAATACCTCAACAGACCTGAACGTCCATGCATCGAGCTACTGGAAGAGAACTACGGCGACTCCCAAGGCCACGTCACAGTACGGCCATCT
131->TCGTAACTCACAGCCTAGATACACGACTCTCCCATAAAAGTGGGGCAGGATCCTTAATCATCGTATCCGCGAGCTGATCTACCACGTCTCATGAGGCTAGAGCACTAAAGGATAGATAGGTTTCTTGTCCTGAAGGTATTCAAGACCATCGCTTAACAAAA
132->GCCCCGATTTAGGATGGGCCGTGTCTTGTTAAGATAACTATTATGATGTACAAATTATGCCCACCTATCCAGGGGCCCTAGAAATAGTCGTCTGGCATACATCCCAATGTGCGCACGCATTCAAACCGCTGCTGCCCCATGGGACATTGAAACTTTGACGC
132->TCCTGTAGCATTGTGTTGTACTACTATTGTGGGCCCAGCTGACCTGGGCGGAGATGGCGGGGATGACCCAGACCATCCAGCGGGTCTCGGAATAAATATCCGATATGGAAGACAGATTTATATCTCCATATGGATTAATCGCCGTAAAATCTGCACCCTTA
133->AGCTTTTACCGTTTTTCGTGATATCATGCCAGACTGACAGCCAATCTCGCCAGGTGGACGGTGATATAGCCGTGTGTCTGAGACCTGGTTAGAACGCATCATCACCGCAACCCATCCAATACAAAGGACCACGAGCTGTAATAGGTCAACGTTAATCACCG
133->TTGAACAGCGGTCAGACCGATTTTATACGGTTTGGAGAGACATTTCGTTTTAGATACGACGGCCTAGGGGCGCATTCATACCTTATCAAAGCCTGCGAGATATAGGATAAGGCAATCACCCGGTACTAGTGTCGCGGAGTCCGCGGTGTCAACACAAATTA
134->CTTTACAGTAGTGCGAAATCATGTCAGATATACGGCTTCACAAGTCTAAGACAGAACAACCGATACGCATTAAAGTGCATGGTAGGTTCTATGTGTCTCATCATGGCACATCAATAAGACATTTTATCACAGAGCTTCGAATAGTGGATTACGATGTCGCG
134->GCCATTCCAAAGGGGACGCTCAAGCGGGCTCCGGGCCACGATTCCTTACATTCGCTCTAGAAGGTCTTCGAAAGACCGCACTCATGGGCCCCGAGAACGCAGGGGATAACTCAGCTTAAATCCAGGATGCCTTTATTCAACAGGTAGTGGAACTACAGTTA
135->GTCAACAATTTAGCAGTTAAGCCATGTGCACGCGTGGTTGTGACCGACAACACCAATGGGATCCTTCCGGTCGAACAGCCAGTCGTTCTATTACTCTCGATCCGGGATGGAAATACTGTTTTATAGGAGGACTTCCATCAATCGATATGCCACGGAACTAC
135->ACTGTTCACCGACTTCGAGATCCCGACCTTCGACTTGGAGTGGATGTCCCGCTACTAGTAGTTCTTTCTCCGCATTCATTGGAAGCTCTACAGTTTACGGACACCTTCCCGATGTATTTATGCTATTAATATTTGACTTTGGCTGCGCATGTTGTTATGCA
136->ACCGGATACATCTGTAATTGAGTTACCAGGGTGGTCCAGGCTTGATATTCTCGGTTTTTCGGCTCACTCCCGCCACCTAACCTGCATCCTGAAGTATCCCGACGTGATTCCAATCACCAGCTTACGATGAAGTGGGTATAATACTGCCGTGAACCCGTCGA
136->AACAAGTTGCAAGATCGATATGGCGCGGTTCTAGTCCAAAAGCGACTATTAGGAAGACTCTTTAGGTCGCGCCTTAGCCTCGCGCGCTTGTCCGCACGTGAACTATAATTGGGGGTGGGGCTCATATATGTGAGCTCTCTGGCTCTATATTAGCGGTGATC
137->GCTTTCGTTCTGATGGGGATTTAGTATCGAGGTGGGCACTCTGCAACACATCGACAGAACATGCGACACCAGCCACCTTAACGAACATCTTAGGCCCGTAGGCCGACGGCGACCTTGTCTTTCCGATAGGCGAGCGCAAGAACCCGGACAGCCTATTACTT
137->GTTATTCGCCTGAGTCCGGAGGTCGGTTTTTGGAGTTAGTCGCCCCGGCTTTATGTAGTGGAATCCTCCGAGCGTGATGTCCTAGCTATGCCGAGCTTAACCAAGTAGGGGACTAATGGTAAGAAAAAAGCATGCGTAACCCCCTAGCCCTAAGAAACTGG
138->GCGTTGAGGCAGTGGGAGGCTACAGCGATAGTTGAAGCATTGATGATGAGTGGAGGCTGTTGTCCCTGTATCCTGCACGCGCAGACCTCTCTTCCTGGACTCACCTCGCTACCTAGCGAAACATGTAAGGCAAAGACCATTTAGCTCACTAGTAGCGAGGA
138->CGAAAAAGTCGGCAGAAAAGAGAGCTCAGTCCGGGTATTCAGAGCTGCCGGGGCACTGGCGGTATAATAATTAGACTGTTATACTCTTTAAGGTCACCCAGTTGTGGAATAGACTATTTGTAACAAAGAGACTATCCGATCTCAGCACCACCTTCGCTGCA
139->CACTGATATGATTAGATGTTGATTACAGTAGGAGGACGTACCAACTCGACTACAACGCGATCGCCTCTCCCACACACATCCGCTTTGGTGCTTTGCTGCCGGAGGTGGAACTTCGCGATAGACCTTTTTCTTCGTCCTCGCCAAACTCATCTAACGTGAAA
139->TTGAGGGATCCCAACATGTCTCTGCTCAGGATACGAAGGCGGCAATCTTGCGAGCAGGTCAGCGCGGCGTGTGCCTATTTAGCTCGATAGAAACGCAGTTCTTAGATTAGAGCTGCGATCAGCGCCGTGCCTTGTCCATGGAAGTAATCGGTCCAAATACG
140->GATGGTGACACAGCGCCTTTACCCAAGACTTGGAATTGACACGCTTGATGTTTTAGAGCGAACTATGTTGGTACCCACGGCGCGGGCGACGCCAGGACACCAGGCCGGTAGGAACACCGGTGTGGAGCTTTAGTAAGTATTCACTACAGATAACAGACCGG
140->CTGGCTAGATAAGCATGATATCGAAAGATGTCGAACTGTTAATATACTCCGTCGTTAAAGACTCCACGCAGAGATTGTGGGCGAGAGCGTTCAGACGAGGCGACTGCTCTCAGGCATTCCGTTGATTTGCTCTTTGGAGTCAGGTGTAGCGATCTCGTTAT
141->TCATGGAGGGTGGACCGCACTCAATATTTGCTCCCGTACGCCTGTACTATTGTAGCTCCTGTGGGTAGGGCAGCCGTTCACACGCTTCGGACTGGTCGGCCAGAAGGTCGTGGAATATACGCGCTGTCCTAAGTGGGCCGTGTAGGATTGAGGTACCTTGG
141->AAGCGGTGAAGCCTTCTAACGCGCAGATACCCACTGAATACACGAACTGACAACCTGAGTAGCGGGATTAGTGTCTCATGTGACAGCGAATTCAGACGACGGAACTCTCGAGGGGATGCTGCCCGCATGATTCGCTACACGCCAATTAACCCGGGCGACGT
142->ACTAGCCCTCACCTGAACTATTTCTACTCGCCAGAGGGGTACGTCCACATGATCTGCGAGACTGGGAGGCGACCCATAACGGGGTTTAATGAATGCACAGCATGCGTGTGATAGGTCATGCATGAGTGGCATCCCGGGCTTGCATTCTTTAACTTCTGTTT
142->CTACGTGTCAACTAAAGCCACCATAGGGGGAGCTACAGTAAGGAGAACACCTTTCTAGACTGTTATGCCCGCGCACGTGAGCTGACAGCTCGCGGCGACGGTGATTTCCGAACAACTGGTCGTATGTACTGACCCCATCCGTTACTAGGGGGATCTTGATG
143->CCACTACCTGAATGCCATGAACTTGACAACACTATCCTACTCCACGGAATCGAGATGTACTACGCTAAATATACAGTGACGCCCCTATCGGCAGTGTGTGAACATACATACTCATCTGCAGTAGGCGATCGCAACCCAGCTGTCCCATCGAGGTTGATCAG
143->CACTAACAACAGGTGTCTCATGGCAGTCAGAGGCAGAGTTTGAATGTCACCGGAGTGAGTACCTTACAGATAGTCGCGCGTGCCAGGGAACATAATTGGAACATTGTTCGTAGCCGTGGCGTCTCACCGTGATCGACAGCTAAATTACTGGATGCATTGTG
144->CTAGTCACACTAGGGTTCTTATTCAATGTAAGCACGGTTGGAAGTGCGTCTCCACGCATCCGTGCGACGCACAAATGGTGATGGGCGAGGAGGTACACACATCGGTCTCCCAACTGGCCCACCTACCCTCGTCGGTATGATGATATAGAACTCGTGTTTAG
144->CTGGTTAACCACGTTCAAGGAAGACGGGGGTAACGAAGTACCAGTGATTCAACCTATGGTATTGCGTCCAGCGCACGGTCTGGCTAGAAACACAGTCTTTCGCGCGGCATTCGTCCGCCTGTCGGGGATGTAACTATAGTTTCTTAGTCCTGGTGTACCGC
145->GGTCTTGTACTAGAAGTCGGGGGCCTGCCTTTACGTTTGCCAGTTTCAACCCCCCCGTTTTAACCAGAACTCACGAGTCTGAAGTGTGAGCGTAGTCTAATATATGGCCTGGTGTTGAATCTACGTATTCTGACAGTGAAGCGTGGGTATTTGATCGGAGC
145->ATCAAGGCACGTATTTTTCACGGCTCATGGATACCGATGAGAGTCCCCTCATGCATGTTCCAGGTTCCGAAGGACTGGCCAGGTCTTCGCGAAGAAGTTCGTTCGCGCCGACACCGACATGACCAATTACCAAGTCGCTACGCAACAGGTCCTCGTGTACT
146->CTCGATCTGGTTGAAGTAGCTATCCGGGCGTGCTTTTCCCTCGTTCCACTACGCGAGGGTCTTCCGTCGGGGCCGTGTGCAGTCATGACGCTTTCCCGCGTTGCCCGCCACGCTCGAGTACCTCAGAGAGTGTTCCGTTAAATTTTACATCGACGAGACCA
146->GGGCAGAGATAGGAACGAAAGAAACTATCACCGGTGGCCCTAGCATTGTGGACGGCCCGTATGTACGTCGAAATTTATAAAAAGACCAAGGGCTTCATGGAGGTGCATATGAAAAGCGCATGGCCAAGGCATATGTGCATGCTACACTAGCGTCACAGCTG
147->TTAGTTCCGCACGTGTGTCCCGAACCGCCTAGTAGGTGTGGGTTACACTTCAATACAACTGAGACTACTGTGTGATCCCAATAAGCGACTATGCCTTTGGGCTTCAGACGGAGATTTCAATGCCAGGCACACCTCATGTACCCGTCGGTTCCGTGCAGTAG
147->GGCAGCCCCTTGAGCGAGCGAGTGGGATAGCGAAAATTTGACATGCTGGAGAACCATTTGATCTCTTTGGAGCTCCTGCATATTCATACGATTAACATATGACTTCGATACGTGTCAGGCACGTCCCTTCGCCCAGGTTTAAGATCGGCACGCACGCCCCG
148->CATTTACGCGGTCTCCGGAAATGAGGGCCTAGACGCTTTTCTTACTGTAAAGGTACGCCCAATTCCAAGATTCTGACGGCGGATTGTCCCAACCGTCGTAATGTTGTCACCCTCCGCGTGATTCCGACCCTCTGGGCAAGAAATCGAGTACAGGTAATTTG
148->ATACGTTGAGTCGTTGTAGAACTAATTTTTGGCCATGAGATACGTATAAACATTCACATGCGAATACATTTTTGGAGACCAGACCTGAGGCCACATTTGCGGCAATCCGTCGGGTACCTACGTAGGGGTTACAAGTGTGCTTTGTCGCGCGTTGAATACGT
149->CAAAGACAGTCGTCCGGTGATGTGTGGGCCTCGCTCCACACCTGGATTGATTGTAGCCCTATGGAAAAATTGACATTCGGGCAGCTCATAGACCGGACTTAATTAGGCGCCCGAAGTCAGCAAAAACCGTGATACTAGATTGGGTCTGCAGGACGACCTCA
149->GGTGGTGACGTACGCTGGGCGCAAGCTGTATGCAAAGGTTCGAATTGATGAGCTCGTGGTGTACCTTGGCCATTCGCCCCACACCTGGATACCTGGTCTGAAGCTGAGTCTGACGTAGAATTGGACCATGACTCGACGACAAACGAATTCCTTAGGCATTG
150->CTGGACAGACACAATCGCGATCAAGGTGCGGTAACCGCCACCGGCGGACGCTATTTCTGATCCACCGTTGCGGTGCGCTGACAGCGCGCGTCTCCTGGCGAGGGCGGAGCGTTATCAGTTAACGATTCGCTGAAACTGGAGGGAACTTTACTTAATAGCAC
150->TCCCCCAAAAGAAACCGGTAATACCGCTAAATGACTCACGGGAACATAGTCAATTAGACTCCCATGGGCTAGTAGCCGCGCCGAAAACTAGTCCGCCCAGGACCACAGGTACGGAGTGTGTTATGCCACAGAAAGCGTTCCAGTCGGTTAAGTGATAGGCA
151->GTATACGTTGTAGTTAGCCAGAGCAACATACGTATCCCATCCTTCCGCTTAGAGCTATCTCTGTATCGCTCCGCTAAACAATCTAGCAGACATCGTTAGGGCATTCCCTTTCAGTGATCGGGTCAACCTTTAGTCACGTCCGATACATTGAGTCGACCAGG
151->CAGACACCTTCATTATGATTATGGCCAAGAGTGACCGAGGCCTGGCCAATCTTAACGGAGACCGTGAACGGTTATGCGGTCAGCCGACGTTGCGATGTTTTTAACATATATGTGGATGTAATATCTCTTCAGTACCGGCACCTCCGTCCGCAAACCAGTGT
152->GTTTGTAGCTCCTTCAAGCCCCAGGACGCCGGGCTGGAAACCCAGGGAGGGTCTGATAATACTCCAGTTAAAAAATGCGTTCGACATAAGTAAGCGCGCAGCGACAGCTTTCCTTAACACGGTGAGAGCTACTAGAACATGCAGAACGTAAAGAGTTTTAG
152->TAGAAGCAGACCTCCACGCCAGATCGGTTTCTACAGTTTTCTAACTTCAGTAATCACTAGGTCCTGTCCTTCAAGTGAGGTCTTGTCACGCTACGGTCATAAGCCTCCATCACTGTTCTGACTCATACCCGAAAATAGACTAGTCATCCCCGTCCGGCGTG
153->GTCTCAACGCATTCCCAATGCCTCTCGCCACCCGAGGCTAGTGTACGGTTAGTCACCGTTTGGCTCTGTGTAAGCGCTAATCCTGCAGGCAGGGTTACATGTGTTGTAGGACACCTGATAGTAGTGCCTTCTCGTCTAGCGTACTGATATATAACCGCCGA
153->ACAGCAAGCTTCCCGAAGACAACAAAAGGGCCTCATTGGCCCGCGTCGGGCCGTGCGGGCTTTCGAAAACTCAGAACCCTACCATGGAATCTGGGAGAACCTATTATCAGGCTGTTGGAACAAATCGTCAAACACATCTTTCACGCTGGAACGGAGTCGTA
154->GGCCAAGTATTGGTTTTGCTCGGCCGACAAGTCGTAGACCAATTGACAGTCCTCATTGATTATTTGTGTCAATTGGATTCTGTAAGACAAGACGCTCGGTAGCGACTTATCCAAAGTGTCCTCAATATTGCAAGGGAGCGTCTGAATTTCACCTCATAGGC
154->GTCTACACCGATTCGGATGCCGTAGGCCAGTCCACTTTACATAGAGCTGGGTTTACTTAGCGCCCAGAGAATCTCCGCAGCCCACGCGGGCCCTGGTGCATCTGGTTGCTTATGCATTGTTCAAAGTCCGATTCACCATCACAAAGGTCAATAACAGTGAC
155->CTTCGCTCTACATTGAACCGGATTTGGACCCACTCAGGCGCCTTCGTGGAGATCGATCGCAGGGGGGGATCTAAGACAGTGAGTACCCAGGAGCCGACCAAGGGTACCTGGGAAGCGTATTGCCGGTCCCTCGGTTACTTGCGATACCTCGTTGTAGATTG
155->CTCTAGCGGAGATTTTTCAAGCTCATGAAGTCGTTACACGAGGACGTTTCGCTGGATTTAGTTGCTTAGGTCACTCCCTCCAATCCTGATCGAGTTAGAAGGAGGACACGAAGGGTAGGTTTTGCTGGGCCCTACAACCCGTTGGTTGCCCAGGAAATTGC
156->GCCGTATGTTCAGAACCCCGGCCGTACTAATACGCGTCAGCTGGTGTACGGACCCGTGGAGTCCTACGGTTGTAGTTCGGAGGGTGCTAGGTAAAAAGGCGAACCAGTGAAAGTTGCACATACGATCGGATTAAATCCGGCGTGAAGAAATAATAAAAGGA
156->AACTCGGCAGCGTAAGTGGGAGGAAAGTGGCTGCCCGTGTCATACAGGGTAGCCCGACGGCCGCATACAATTAGCAGTCTAGTGTACAGATGATGGTATTCACAGTTCCTGCTACACCCAATATGAGACTGGCTGCAGTACGGGGCAGCTAGCATGTGTGA
157->ATTTAGTCTGTCACTCAAAAGATGGAAGTCGTGGTCGGTACGAGGGGACGTCTACGCGCAGAGGCACACCCCACGAAGTCGTGTAAGGTGAGTCGCCGAGTTAGCGCACTGAGCAGTACCAGCGTGGTGCGGCCCCGGAGGCAGTCGGGTGCGCTAACCTG
157->GAAAGTGAGGCCGCGATGTGAGTCCGGAGGAAGGACTCTGGAATGCTATCGTGCTCTGTCCGTTTGATCGTGCTGCTGAGATCCACCAGTATAAGGCCATCAACGAGCTTCGTACCATTTTTGGCGGGAGGACAGCCTCTTTTTAACACAAATACCTGTTG
158->GGGCAGAGCACCCCTTCATCAAGAAGAGTTGGGGGGTTTTATTAATGAAAGCACGCACACAGTAGCCTGCTCAATGATGGGTCGCCGGTCTGTGTAGACGCAACCACGTAGGGGCCAAACCCGCTTATCTAGGCCTGTTGTTTCTTGGGAACGAGTGTAAT
158->ATAGTTTGGAGGGAGGTCTCAGAGTATCCCTAACTGCTCAAGTCGCCCTCCCACGATGGTAGCTTTGACGCAGTGACAAGTCAGCTATCCACAAGATTACTTCTTTTCGCAGCATACTTCATAATAGGGGGATGTTTCCATTCTCGAGGCTAATGATTCTA
159->GTGACGAGCCCCTGCCATACGTATGCCGGCCAATTGATCACACGGTTCTTATAACACAAGGGATGCGTCAGCTGTGTTTAAGAGTCATCTGCGTCATCTAAGGGTCGATAGAAGGTGTATGTAGATCGAGGGGCCAGATGTCAGAGCGACGTTGTCAGAGG
159->GAGAGTTACAGGCAAATCCTCAGACTGTGTCGTTCCATGCGCCTACTTAGCGGGTGCCTACCGCAGGCTTTAACAGGTCAAGAGTTAATAAGAAGGCGCAGCCCGGGCGCAGGTGTTCATACTCCCTTCCGGGAATATTGCAGCTCCGGCCCAAATGATGC
160->CCCTGTCTGCACTGCAAATTGCAATTCGATCGGTGCGAGGGTAATTAGGACAAAGTCTTGCTGCCGGCCGGCAGACGCCATGCACATCTCCTTTCCGAAAAATACAGAACGTGATGGCGTACTATCAACATGCTGCACAACGAATGCTAGGGTGCAAGATC
160->GGCACCTGCATTTAAGGTTCCCTATGAATGGATAAGACGCATAGTTGCATGTATCGCCATTGTACACCGGCCGTTTACTGACCCCATCTATTTGAACACGGCGGGCTCCTGCGGAGTCTACGGACGCGCGGGCCCGACGAGCCGTCATATAATTTGGGCCA
161->GCGCCAAGCCAAGCCTGGGAGCTCACGGTAATGGGCTCAGCGCACCTAACTGCTAGGCGGCGCACGAATGTTAATCGGGAGGCCAGTTGACGATGTAGTGCCATGTGTCTCCAAGGGACGATATCTATCCTACTGTCGGTAACTGCATACGAGGACAGGCC
161->CCCTGATATCTACGTTTACTTTGGTGGCAAGGCTTTTACTCTCCTATGGAATATTTGATATTTCGTCTTAGAGACTTGTCGGGCTTCAGTTGCGCTTTAATCGGCGGCAATTTCTATTCTGGGATTGGTACCGGATATGAATAATATCGCTCAGAGTCACA
162->CACAATCAGAAGTAATCTTGAGACAGTTCGGTGCTCCCTTAGCAGAGTCTTTTCCGGACCTTTACCCACTATAAATCCATCTGCCGGCTAGATTCTAGATGCCGAACCGCAGCCGAGCGAAGATATTAGTAACGTACTGGGTTGAGAATATTGCGGCACCG
162->AGAACCACCTTACGATTGCTGATTGCTGACCGACCTCGGTTCCAACTTAAATGTAGGAGACTGTCCCCCTTAAGCGTAGCAGGTGAAGAGATAAGTAGAGAAACGTGTTGGATTACTTGTGGTAAAACATAGGATAGCCCATTTCATTGGGTTCAGATTAA
163->CCACCTTTCGCTAGTAGTATGCAAATCTGGAGGCACACAACTGTTGTAGCGAACTGTATAACTGACAGACCTTTCCTGCCACACGAAGTTATTACATCCAGAAACACCGGGGCTCAGGCGTCGAGAGACAACAACCCTGCACCCTTGCAGCATAGATTTCG
163->TAGGGGCCTAGGGGGTTATAAGCCTCGACGAGGGCGGTGAAGAATGGAACCATAGTGCCCAGAGGCCCGAGAAAACTAACAAATAGTCCAGTGGTGGACACTCCCAAATGGGATACGGCCCGCCGTAGTAGATTAAGGGATCGACGCAAATCGCGCGATTA
164->AACCCCGATAAATCAAGTCACGAGTGCCAACCGTAGGCCCCACGGCCCGAGGTGCGCATAAACATTAAAAGTCACGCCGCTGCTTGGGCTCAGCGTGAGGTCCCGTAAACGTACACCTGATCGCACTAGTTGCTAGGTATACCTATTGATACCCAAAGCAC
164->TCGAGCTTACTGTTCCTCTACTATCCGCCAGTGCCCTGGGAACCTCCGGTCGCATGTTGGATACGAGTATGGCTACCTATTTGCAATACTTCGACGTTTCCTCATGCTCATGACCCGTCTTTAAGGCTAACGCTTTCGTTAGCGAGAAGCCGAAGAATTAC
165->ATCGATCAATTAACCTGATCTACCGCTCCATGATGACACATGTCAAGTACTCGGAGGCATGGTTTCTGGAGGCTGAGGGAGGCCGGTCGAGAGGTTTTTACGCGACACTCACTGGTATGGCTGCGTTCAGCAACACGTAGGGCGGCAGGCTCCTTGAAACT
165->GCCCGCAATGTACCTCACCGCAACAGATATCGTTGTTTGAAGCGTGCTCCCTGCAAGGAGGCTCTCTAGTCTACCAAACGAGCCCCAAGTCCGAGAGCGTCTCGAGAGCGATGTTGACTAATTACCTGTTAGCGCCTGTTGGTATAAAGCCTCGTACTGCC
166->TACCGGGTGCCGCGCGCTACTGCTGAATATAAAACATGGACCCTGTGTCTCTCGGTGAGCTCTGCTGCATTTGGATGTGCATTTACAGGCTGTAACCGGAGAAGTCATACGTCTGTGAAGGAAGCCAGGTGGTCGCAGCCAATTCAAACGTATACATGGGT
166->CTAATAAGGGGGTTCCTTAACGTGCTGCTCCGGGCCCTGCATATAGGAGTGGGGGAGGGATGTACTTCGTAGATCATGATCCGCGCTGGGGTCACAGACATCCTTCATTGAAATCTCCAATTTACTTGGTCAAAAATATACACGATAGAATTCGGCAAATG
167->TTCATGTTACGGCTAGCCCGCAATGCAGTAGTGTAGGCATTTCGGCTATAGCGCCGGCTGGCTGCAAAGGTGCTGCATGGGCCGGAAGTTTGTTGACAAGCAGCTTTTAAAAGCGAGCAATCGGGTTCGAAGACTCCCCTCGGATCTCTAGACTCTCACCC
167->GATGTGTCCCAGGATATTTGACCTGGCAAGCAGATATTATACATATCTCAACTCTGCGATCGTCGAAATGCACCCGGACAAGCTCCAACCCGGGCTTCCACCAATACCTGGCTCCTTCCTTTCCGGTAGCACATTCAGTGATAGTGAATCCCGCTGAAGTC
168->ATATACACTTCTGCTGTATTAAGCGTGGGCGATCCATGGGCGGACGTGCTCTCTCGGATAATGCGCAGGGCACTCGCTAGCGACTAACAGGTGGGTCCCGAGTTGTTACCTACCCAGCAGCATTTTCGACGAGTGGCGGCTGCAGGGATATGGCAATTAAG
168->GTGTAGGAACTGGAAGCAAAGAGGATACACGTGACTTATTGGGTTACGTAAACACCAAAACGCGGAAAGCTACTGAATAGGTTTCGCATAGTCTTATACTAGCTACGCGCTAGGGAGAGTACTCCGTGGGGCCAATCCAACGTTGCCTGGACTTACTTAAG
169->TTATTAAATCACGCTTTGCGGTTCTAGACACCGAATCGGTCCGCACTCAGGGGTGGAGACGGGTCGCCGCTGCTAGGGCTGGCGGATAACCGGAATCGAAAATTTATTCTGGAACCCCCGTCGTAGTCGCGCCATGGAGATCTGCCGATATCTCGCGAGTC
169->TTATCTCTGGAGATAGTATCGCTCGGTTATTGGGGCCGTTTCTCATGTTCTGTAAGCTCACACATGTGACGTTGGTAGCTCGCGCAAGCCGGCACGCGAGATGACGGGTTCACGGCTCTCTTGTATCTACAACGATCATCCCCGCTGGCGCTCATCCGCGA
170->CCTTCACAGTAATTGCGGGTACACCCGTCCCCCCGCAGGCGTAGGTATTGTGTGCCCCGAGTGGTCGAGTGACAAGCGTAACCCGCTGAATGAGAGTAACACTTCTCTGTTCCAGGCGTGACCCCACAGGTTGGGGAGGGTTATATTGACCGTCACGAAAC
170->GATGGTAAATTCATGGGAACGTAAGCCTGCGGGATCCCCACGAGTTGGCAAAGCCAACGTGGCTTATGGATGGAGTCCCGGCGTCTGTCGGGTCCCCGAGGTTGAGAGCGTACAACCGATGAAGGGGATAACTTATTTAGATTTCCACAGAAGAATTCTTG
171->CATTGGGCGCCTATACTATGTGCCGTCGTGTGCCTTCTACTACTGGCCCACGAAAGGTTTGACCGGATTCGTGTCGTGTAACGTCTCTCAGTCAACCCGATACAAGGGATCCATGACCTTGATTTTTTTTGGTTCTACATTGGCGGGACCCGACACTTTGC
171->CAGAGAGAAGTGTATTCTTTGGAACGCGTGGCTTCAGTACGCCGTTGCAGTGAGCAGCAACACTGCCGGGCATTCTTATGGGTGGTTGTCTAGTCGTCCAAGTTGGTACAAATCGTTTTTTAAGCGTAACTCGGATCTAGGCTCGCGAGAGGCGGACCCAT
172->CCGGATACGTCCTGACCAGAAACTAACTGTCATACGTGTCGGCCAGATGCACCACACGAGGCGAGCCACCGGCTTGACTGCTCATAGCGGTCACTTACAAGACCGTTAGGTTCGGGCCTCAACCGATTGCCCGGTCTCTTATATCTACGTCAAGATTTCTC
172->ATACAGGGCTCCGTGGTACAGATTCCCCTAGGCCCAAACGGACATGCCTATGCAAGAGGGTCTGCACAACAGGTCACAGGCTTTCAACCGTACCACGTAGTATCTTGTTTGTCTAGGTGCTTGGTATAACTACATTGCAACGTCCCCATTGTCGAATAGTT
173->TGCTCCCGGTTTGCACGTACCCTTGAGACATCTGGAAATTAGAACCCTCCGTAACCACGGAGTATGAATTCCTTCTGCCTCCACGCGTATCACCATCGTTCAGCGCAACCTGTCGAGAAACCCGCACGATGACAGAGACGGGAGATATAGCACCGGTTGCC
173->TTACTAATGAGTTCTTACAGAGTTGCCTATCCCGATGGTACTTGAACCAGCTGTTCTCTGCCGACGGCCATTCTGTAGGTTTCATGCACAGTACAAATCGGCGTCCTCGAATCTAACGGATCGTAAATCCGAAACCAGCTGAGACAGTATGTATATCCGCT
174->TTACCCTTTTACCCCGAGTCCATGTTCGGTGTCGATTCCCACAGGTCGTAAGGAACAACCACGAACGTTATCGGACAGATTCATATACTACGGTCTGCGCCCACGGGTGCTGCGTTTATTTACCAGTTTCCCCCCTGTAAGAAATCCGGCATGGAGCATGA
174->CAAAGCGCCACGCAGGGCGAGAACTTGTGGGTACACTCTGTTTTTCGTGAATCACACTAAGTGCTTGTGCTAGACCGAAAGGCAACGCGCTATCGAAAGTATTGTCTAGTCTTTTTCAGGCTTTGCTCGGAAATTTAGCACTCCGGGGGATATCTAATCCA
175->CGACCTACAATCAGTATTAGCATACTAAGTTCTACCTGCGGATGTGTCGGGGCGACACGTGTGATACTACTCGCTCACCTCATGTATGGACACAGCCGGTCAAGGGTGGAATGGTTACGGACCATCAGCTTAGCGCAAGCTACAGGACGAGTTTCGGTGAG
175->ACAAGAGGACACCTAGCATATGGACGATACGGGAGGTCAATCGTATATTAGGGACTAACGTACATACAGAACCGGGTAGCTGCACGTTTCAGCTATGGAACGCTTGTTGTTTGAATTCGGTCCCGAGCAAACCATAAAGGCGTCATCAGCGAGGAAGGTGA
176->ATGCGTAGTTTTCAGATACTGCTGCCAGCAGTTTAGTCGCAGATGTCGGTCCCGGTGTTAACGACCGTCACAATTCGTCGTTTTGTGATGATAACGATGCCTACCATCGCAACTCATTTTTGTCCGCGGTATTTTTTTCAAAAAAGTTTGGATATCGGTAG
176->TACCAGGTCTATTAGCCTCGATCAGTAGTAATGAACTCGTCACTAGGTTCAACTCATTATCTTCGAAGCGAGCTTCTAAGTACAGTAGACCATGTCCCTGGGATCTACGCCAAGACTTGTAACAGGAACTTATACGCTGACAGACAATAGAAAAATGAGTG
177->TATCGTACTGGTACCACAACGTTCTCGTAGACAAAATGACGATGAAAGACTCAGCTTCTTTCGAAATTGGGCGTCGATGTCGTCTATAATGTCCCTCGAATTCTAATCAAAAGATCTTAGTAGCATGTACCCACGAGTTGTAATGTTTCAGATTCCGCCTC
177->CGTAGCTGTCCACTGGCAACGGACCGGCACACATGCGTTGTTACTGGACGTGGGGTGTGGATCCTTGCTTGCTGCACCCAAATGCCGGAAATTGGCCGAGAGTTTCCGGGTTATATCTTTCTAACCCTCTCTGGCATCATCTTATTAAACCCTGCTGGATG
178->ATTTCGCACCCTTTCGATTCAATCCAATTTATCCTCGAGCATTTCACGCCCTCTAGATTGTTGCTTGCCAGAATCGGACGCACATCAATGCAGTAAGGGGTTAACCGGATAGCACGTTGGAAGCTCGGAAGCGAGGTTTTCGTGAAGCAAGCATGTGACCA
178->TATGGTGAACTTTTGGGGACTTGGGCGTCACGCCGTTCACGCAAGTCTATATCAGACGCGTAAAGTCGTCGCATGGCTGCGAGACAATTAGCACTAAATGATTATTACATAGAGTGTAATGATCCAGCCACGCAGAATGAACGCCTGTCTCGTTGGGACTT
179->CTGGAGTGAAGGGGCTCCCCTCTCCCTTCGCCGTCCCAGTGGACAGGTCAAGACTCCGAAACGGGGTTGACTAACCAAAAAAGGATAGCCCAGAATACTTACTGTATAAACGACCTCTATATGCAAGAGACGGTAGCTTCCACTGTGTGAGAACATCTGGA
179->GCAATCAAACATTGGCCACGGAGATATCATATCGTTCGTTGTGTACCGGATCGATGGGATGACTTGAAGGGAATTAGTAAGTCTCTAATGTGGAGCAAATCCATCCCTTGTTGCCTCCGGCCGGACCCGTAATATAGCAGTCCCTAATGGGATGTAATCGA
180->GGTATGGGTTTATATGTAAGTATTAAGGGTTATAAAGACTCAAGGACGTACGCAACTTTGCCTCTTTTATTTGGGAAGTACTAGACAGTACAATTCTAGGAAATTTGGCCGAAATAATCACTCCGCGCACTGCATAATCGCTTAGGACTAGGGTTTACCAC
180->TTACTTCATAGGGGGCCCTGCAACGAGCATTAATGATCCTATTCAAATGGCCTGCATGCTTGAACCACCAGATGTCAACCTTGGGCGCCTTTTGCAGCTAACTATGTATTAGAAACAGAGTTTAGTAGGCAATCAACCTTGCAAGATGGCAAGAACTGCCA
181->TTCGCCGTCTCACGTTTCATTATTCAGGAGGGCGCAAGTCATAGGGCCCTTTTGCATTATGTTGGTCCTACCATGGTGTGCGTGTGAGTTACGGTGTTTTAAACGAAGGTGTACAACACAGGGTACCAGACCGTCTCGCTACCATAGAACATTGAAAAGCG
181->CTCCATTCCGATCCCGGTCCACGCCTACCCAACAGGAGGGCTTTAATTGGCTGTGCCAGTGCACAACTCGACCCAGCCGGCCAGCGAGATTACTTGAGCTTGTTGCGAATACTTCGATAGATTGTTATGCTTGCCTCATAGTACATGAGTAAGTGGTCATC
182->AAGTATCTGATGCTCAAACCAGTGCACCGACTCCCTCTATGGAAACCTCTTATACGTATCTAAAGGGACTGCCGATTCTAATACACCAACCGTGTGATTAAACTGCCAGTCAGTGTAACAATTTCCTGCTTCTCACCTTTGACCGTCTGCAACTGACGATT
182->TCCCAAATGTGTGGACGATTAGGGTGTACTGGACCTAATACATGAGATCACGCAGAGTATCATTAGCGGTGATGTGCTGTCGCTAGCTAGTAAAAAGGCTCATAGTAGCAGTCTGCTTAGAATACATGGTTACGGTGTCTCGCGGTCAAAGAGGTGTGCGA
183->ATGCACGTTTCTGGTATCCTACTTCTATTATAGGACCCTTTCGATCCCGTAAGCTCTTTTGCACTAGAAGCCACTTGGCCTAGAGGGTTACGCCTGTCAAGCGAGCCTTAGAAGGATTAATGTTCACGAAGGGGCGATGAAATCCTGGCTCTTGACGCTAA
183->GCTGCGACACCGAGTTTAGCCTGTAATAGATTGCGTAGGTTGCGGACTGCAAGAGTTAGAAAACAAAAGCACACCTAATCTACCGTTAGTATAGACTTCTGGAAGCGGACCGTCTTAAAGAATAGCCACAGGGACAGTCATCGATCTAACAAGGGGAAGCC
184->CTTCTGTCACGTCTCTATTATCTGCCAGCGCCCCCTGCACCCATGCCAGGCATAAAAAACGGCATAGTCACTCCACCAGTGCCATCAGCGTGCATCTAACGTGAGGATTGTTGGGTCCGGCGTAGGGACGTGCCGAAGGTCTACTAAATCCTTCCTCATAC
184->GCATGAGAGGGTTGTATCCGAAGACGATATTATACATGTTATGATGGCTAAACGCCTGTAGCAAGGACCGTTCAAGAATAGATGGAGACAATCGCATTGGCGTGAGTCACTTCGCTTTGGCGCGAGCGGTTGTAGGTTCTCTGATGAACGAATGGAATGTG
185->GAGTCTTATTTACGCACTGGAGCTCCGTACTTCGCACGCCCTAAAGGCTCTGCTCGCGTACACACCCAAAATTTAATTACCACCCTAGCAGAGAAGGGAAGGTTGTTGCTTTATGCCGAACTGCATTTTCGGTTTCCTTAATTCTCCTACTCTATGGTACG
185->ATCGATGTACGGGTAGCCCTTCGGATGGCCTGTGGGGCGCCAAACCTATAGCGATAAATCATGATCAGGTTCGACGACCCGAACAAAGGGTGATCGCTCCAGGTCACCCCTCCCACCTCTTCTCAATACGCGGCCAACCATTTTATAGACTATATGTCTGA
186->ATGTAAAGGCAATGTACTGCGTTCTAGCCAATAACTGATGAGATTATATCGGCTTAGCGTTACGTTAGCCCGCTCCTCCTCTCCAAATTTGAGTTGGGAGTGTAAACCCAAAGGCAGATCCTTTGTGATGATGAGTGACAGGAGGAGGATCCGTGTGTGCT
186->AACCAGTTTGGGAGCGCCATTTAAGCTAAAGTAAGCGAAGAGTTCCGGACTAAAACGGATCCTTGTGATGCTGGACAATAGAATTCAACAGTGCCTTAATGCGGAAGGAGAAGCACGCACGTGAGAATGTCAATTAATCCAACAAGCGGCATACGCTGCCC
187->AGTTTGTCGCCGACTGAGGGTCACATTCGGACAATCACCCAACGGAGTGAAGCTGGTGGCATGCCATGGATACAACCCCTTTTGGGACCACTGGAAGAAAAGAGGGTTTCCCATTCCTGTTGCATCTGCAAATTGTGAATGGAATGCGTATTGAGTATCGT
187->AGCTAACATATCTTTATCTTCTTTAACAGGTAGTTTACATGTGGGAATTAGTCAAGCTTGTTATTTCTTGATCTCGAGGTTGGACGAGGTCGCTATGCTGCGGCACTATGCATAAATAACGTTCACAGCAATAACGAACCGAGGCGCAAGTTGCGAGGCTT
188->AGGATTGTGAATGTGTTACTGCCATGTGAACCGCTGGTGTGGCACGCATGGCGAAGAACTGGAGGGGAGTATCATATTGTTGCATACGTAATGGGTAATTGACGAAGTCCTGCGTAAGACGCTCGAGGAAGCACTCCTCAATTCACTGAACATAGCCCGGC
188->GCGATAGGAGATTCGCGTAACAGCCTGGTGATGCGATCTACCCTGGTGTGCAGAGTTGCGTCTTGACCTTATCATGCGTCCTTCATGCTTCAGGAGGCACCTATTCGCCCGAACGGTTACATGCTGAAAGTGCATGCCAGGGCCAGGATCCGAATGTAATG
189->TCTACGAAAGCGTAGGAGGGTTCCTCCCTGGACGTGAAACGGATAACCGGTGGGGTACAGCCACCCTATAGGCTGCACACCGTCGGGTGGTCCGGTGCATATGCCGGCGCCGATCCTTCCCAGCGCAGTACGCAGGTAGGGTGGAAGCGCGACCCCTATGA
189->TATCACACAGAATACTTCTGCTACTCGTCAGTGGTCTGGATCGCCTAGTTTTACTGACGCGAGTTTGCTAGTGGACTTTGACGCACCCGTAGGTTTAGGGTGCACATCCTGCTTTCCTCACACTACCCGGAGAATTATAGCAGTCGCGCAATGAAGCATGC
190->ACCAGGAGATACAGTCGTTCAGCTTGGTCGGACAATTCTACATATTGCAATCTAACGGCTTGGTCCATAATGTTATGCAGCAGGGAGGTGTCTGTGAAGTGGTATAACCGCCGACATCGTAAAGCACTGTACAAAACAGTTTTGTTATCGACGTCTCGTGC
190->TTTCTTAAGGCTCCCTGGCGCCTCATCATACGAACCTGTACTAGGGCAGCCGTGCGCCCCGTCCAGCAGTTATTCGGGGGACTGGGCTTGGACAGCTCAATATCGCGCATCAACCTGGGAGCCAAGATTTGTTGCTGGTACATGTGAACCCTGGTAATGGG
191->CGGACTGACCAGCATGCTAAGAAGTAACATTGTCTCATCGTGCCTACGTCCGGTGAAGCAATCGTTGCCGAGCGTGAAAGCATCTTGATTAACGATCTAGATTCATACCATACGAGCTTGAATCGAAATATGAATGGTACTATCACAAAACTCTCCCACTG
191->CCCGGCACATCCTTACTTAAAGGGGGTGACCAGCTTCCGTGACGTGGACGATGGGCGGCAAAGGTATTTAGGTGACGTTACGTAATTGTATCTATGCCGGCCCACTAACATATCAAAGACAAGAAGGCTTCGATTCGCGAGCTCTTTCCCCGAAAGAAAAA
192->172
192->135
193->146
193->183
194->141
194->181
195->158
195->167
196->185
196->191
197->152
197->186
198->178
198->160
199->187
199->169
200->153
200->144
201->140
201->142
202->139
202->131
203->147
203->156
204->137
204->174
205->143
205->170
206->179
206->155
207->157
207->136
208->176
208->159
209->154
209->190
210->150
210->138
211->171
211->145
212->188
212->133
213->189
213->173
214->177
214->149
215->184
215->130
216->132
216->164
217->165
217->163
218->134
218->162
219->128
219->182
220->180
220->161
221->168
221->151
222->148
222->129
223->175
223->166
224->214
224->215
225->192
225->196
226->221
226->201
227->216
227->220
228->217
228->204
229->222
229->193
230->199
230->203
231->200
231->194
232->211
232->205
233->207
233->208
234->197
234->223
235->206
235->213
236->219
236->195
237->210
237->198
238->202
238->212
239->209
239->218
240->227
240->225
241->233
241->230
242->224
242->237
243->231
243->228
244->236
244->239
245->232
245->235
246->238
246->226
247->234
247->229
248->241
248->244
249->246
249->242
250->245
250->247
251->243
251->240
252->249
252->250
253->251
253->248
254->253
254->252"""
#     string = """128->CCCAGGTTTGAAAGAAGATAGTCGCGCAATGCGGCTTTCGTGGCTTGAGTATTGACGATAGCGAATTCTGCCGTATCGCACGAAAGACCGGATCTCTGGCAGGCAAATTGTCCGTTCTGCGAAGATTTGCAATTAGCGTAGTCATCTAGAACTCCA
# 128->GGTGCTTAAAGATCTCGATGCTCATGGCAAACCGGCCCACACACGCAATTTTGTCGTCGAATTCCTCGAGCCATCATCCTTTTAGCCATGGAAAAGCTCATTTGCTGCCCCTGTAGATCTTGGCCCAACACATCCAGAATGCTTGAGAAACCAACT
# 129->TAATGCTTTAATGCGGTGTTGAAATCAACCTTAAACGGCATATCACAGCAGCCGATACTGGCGTTCAGCGGCAAGTTCGCTTCGCTAGCTGATCGCCGACGTTCCTAGCATTAGAGTAACAACTTAGCGCAGTGTATCCATGCTGTATACTGCCGT
# 129->GGGTTTCTTGGCGTGCCATGATCAAGACGCTATCCTAGTGGCGTAGAGGGTAGGAAACGGGTACAATTCCGAGACCCTCCTTATTCCCCCAGTTTTAGTCCTCTTTCCGGATTAGTGTCTAGGAAGCCGTCCTTCAATATTCACCAGAAACGGTAT
# 130->CGTAAGGAGCGTAGCGTCCAGCCTGGCCGTTTGGTTCTTGTAATGTCGTTCGTCCCTGGGGCAAATCTTCTTGAGCCTTGATTGTGAGGCTCAGGATAATCGCTTTACGCCGTCCGCGCCCACAGTCGGCCTACCATGCGTTAACAATATCGTTCG
# 130->AATCGTACCGAGACTCAGGGGCTAAAGTCGGGTGCTGCACGCTAGAGTGTTCATCCAATCCGGGGAGGGACACTATAGGTAGAATAAGCGGTAAAAACCTTAAAGACGTAACTATCAGGATGGTGCACGGTACGTGTAAAATTTAGCGCGTCGCGT
# 131->CTGATGTTCCGCAACGGCTAGGTGAGGGAGTGCTGTTGACGAAGAGCCTCGATATTAGGTACACTCCTCCAGTCCTTCCCTCGACAAAAGGCCGGTGCTTGGGCCCACTGTGCTACCATCCACTCGGCGACACGGCCCATAACGAGCGTCCCCTGG
# 131->ACGCCCAATTTACGGACAGGGATCGAGATGCCCTATTATCGAAATAACGACCCGCATATATGGTGTCGCTGTCGGTAGGCGTTCTACTGTAGCTCGTAAGCACTAACGTGCAGCAGCGTTATGGGTAAGCTGTGTGTTAACCTCAGGGTCTCCTGT
# 132->GTAGACACGATCACTAGTGGGAATATAATCGTTCCTTGTGGAGAGTCGCCCCCGATTTCGCTCGAGCTAAACCGAGGACTCGGGTCCTTTCGACATCATCATAAAGAACCAGTAGTAAGATGCTCAAGCCAAATCTTTACGCTACCCGGGGGCCTC
# 132->GTGGCCTAGGCCTTACTGTTGTAACGATGAGCTCATAACCACTGTATAAGGGAACTGTTCCAAAACCTCGCGTCTTTCGTTCCATTGGTGAACACATCTTAGAGCAAACGGGCTGATAACGCAGTCCCCTACAGGGTCAGCTGGCATGTAACCCCT
# 133->GGGTACGAAGTGCCATTTTCGTGTCAACGGAGAGTTGTCGTCAAAACTCGGGTCTGGGCTTCGTGATGAGCGATAGCGGAGTACATAAACCACTCGTATTTTACCCCAAACCAGAGGCGGCCAAAGATGCAAGCTACATGGTGTATAGCCCTAACT
# 133->TGTGAGGTCTTCCAGGCACTCTGGTGGGCCCCAGACGTTTGGGACATAGTGTAGTCATTAGGCTTGCAACCCCGTACCCGATGCAGTTACGACTTACTGTCATCACTCTCTACCGCTCCTCCAATGATGCAAAACGCCCGAATGAGGTACTCAACC
# 134->AGTAGTACTTAACCTGCGCGTTTTTTCACCACAACAAGTATCAAGTATATTACGAAATAAGATCCCAAACTTTATGATCAGTTACTATGGGGCCACCCCCGAGTGCCCCAAGATCAATTGTCGACTATTGTGGAGGTGTTAATAGCCTTTGTACCC
# 134->GTTCTCGGTGGCCTCGGTATGTGCGGCAAGCCTGTACAGGAGATAGAGAAGGCGGGGTTGCACTGATGCCGCGCTTGGATCCCCGGAGCGTCACGCCTAGCCTAGTAGGACTACCCCGCACAGTTTCTTAGAGCGAGCTGCGACTAGTAAACCAAT
# 135->GCAGGCGGTTGCTGCTCGTCCCGGTTAGAGAAAGCAGATCGATATGGTGTGTTCAGGGATGGCGGGAACTTTAGGCTCTGTTTATCTTATGTCAAGAAGTATCCTGGGTGTCAGGAGACTCGTAGTGAACCGGGGTGGCATCAATCACCGATGCGG
# 135->CGAATCCGAATATTAGTTGGAGTGATGAACAATATCCTGCCATGAGGGAATGACTTCAGGTTTGTCGATCCTCACTCAATGGTAAGATTCACATGGCGTCTTAGCCCGTTACATTCAATCTGGTATTTCAGAAGCATACCAGACATCTGTGCGCGG
# 136->AGAAGCACCGGCGAGGTGTCCGGATACCCACCAAGTAAATGTGTTTAGAGACTTCGTCTCAGGTTTGATCACCAAGTTCTCCTTCCCCCCGTACCAATCTACCGCTCCGATTATTGGAATTTCTGGCGACGCCCACCGTAACAGATTTCGTATAGT
# 136->GTCTCGTGAAGAACACGCCGCCAATCGTAACCAACAGATGTATACGGGCTAGTGAATTGGCTACTGAGGCCTATGAGATCGGGTCTTAACGTACTTGTGAGAACGTACGTGGGGTCACGCATTAGGACGACGACCAACACAGATGTACGGGATTTA
# 137->TCACTTCTGGACATAGTCCCGTTATACCGGGTTCGCGGGCCCCATTGATTGACCCAGTTACCCAGTCGTGAATGATCCCAAGTTTGAAGCCGTGTCACATTTAAATTCCCGCGCTCAAAAGCGTAACCGGTGATCGCCCTATCAGCCCACGGAAAG
# 137->GTTTGACTTGTATCACAGACCAGATAACGTAGTCTGAACGCAGATGTGTGTGAGGATGAACTTACCTGCTTCGGAATACTGCCCGACAGCTTCGCGAGTGTAGCGCTGCAACTGTGTATGAGAACCAGGTCAGCGGCTCGGACGATATGCATGAAA
# 138->GGGATTACTAGCCGCAAAGTAACGTTCTAAAGCCTTTTATGTCGAACGACTGAGACTGGGTGCGCCGCAGGCTTTTAACCCGCCGTCCTGGCGCACGTTTGTAACGGCGAGCTGTCAAGTAACGACCTACAGATTCTGAATCGAGTAGAACCATTC
# 138->CTCTAATGGGCTCTTACCGGCCGTCAACAACGTAGGATTGCCGACTATTAGTCCAGAGTTGATTATTGAAACTCTTGTTTAGTACAGACACTGTTCCGGCTGGAACCCCATAACGGCTAGTTATAGTCCTTCCTACCATGGAACGCTCGCCACTTC
# 139->TACCCTCAAAAAAAGCCTTATTGGACTACCAGATAAACAGTAATTCGTCCACTGACTGTTCCTTTGGCCTCTACCCTAATTTCATATCTCTGTCCCAACTGAGGTCCTATGGCGTGACGAAGCTGCGCCTCAAATGATCCTATAGCCGCGAACCTC
# 139->CCAGTAATAGCTTAAAAGTCGACTTGTGCGAGAGCCGTCCACTCCCAGAATTCGACACCATACTGGCCTGAGGCAGTAGGGGCTCATAGTACCGCTGCAATTCGTTTATGACGATCGCTCTTCAGCCTCGACTTCATCCAGGCAGAAGGCGTCTTC
# 140->GACTCCCCCACAAAATGCTTTTACGCAAATTTTTGGCCGGTTCCCACTTCAAGCTGCGCGAAGGGATTACATATATGTCGCGCGCCTCTGTGGCCTGTTAATTGAAATCGCACACGCCTATCAGAATAGTAGTGTGCCAGGTGGTCGATGGCCTCT
# 140->AGTCAACAAGTATGATCCGCCGGTTGACCGGACTCCCTCCGGAGAGTACGTGTTTGGGGTCCGACAGGCATATTCGCCGTTCTCATTCGGCAACTGACCTTCCTCCGTAAAGGAGTCCGTGTAACTTTACGTACGCCTAGCTCGCTTTTCCGTTGT
# 141->TTATATAGGTTGGATAATTCAACCATGATACGTGCGCCCCACCCGGGATCCTGCAATGCTCTTGGATATATCTACATCTGCAAGATGCACCGACGAGCGACATATAGTTTGTGGGATTGGTCTGCAACACCTGTGTACCTGGCATCCTAAAACACT
# 141->CCAGAGTAAATGTGTAAGGACCCTGAGGTGTGGGCAGCCTAACAGCGTCTCCTTTCGCACAACCGATAGTTGACGTTGATATAGTCCCACACTCAGTCGGTGATTAGATGCAAAGCGAGCAATAACAACACATACTAATGGTGGCTTACCATCCTT
# 142->ATTACATTAATGGCGTGCCGATTCCTTACTTTTCTAGCACTATTAAGTGTGATTGGCTAGTTCTGATGAACTGTAACGCCTTCATACTTGAGGACCCTGATTGTCTGCTTATCCCCGGGATTAACTAAAGTCTGGCTGAGGGATAACGTCATACAT
# 142->CAAATGGGCTAGCAGTTTAGTAGTCAACGAGCGTATTGCAAACCATCCTCATGAAAGAGATAAGACTAAGTCGGGCCCCCTGAACGCGACGACGCTCGCTACGAGTTCGGATAGGATGCATCGAAACACCATCCCTATCAGCTACGGAATCACTCG
# 143->ATACCACCGAATCTATACCGCCAAACTGAACCCGAAAGACGCATGTTCAGTGCGAGGCGAGTGAGGTCGCCACCCGAGAAAGTGGAATTATAAGGCGTGGGCATTAGAAGCTCCCTACAACTGGGCGCATAAACGTAGTCCCATGTCGTCGTTACG
# 143->CTCGTACAGAACTAAACCTTTAAGTCTTTCATCCCTCGATAGCGTGGATCGGTAGTGTCCGGTGGCTATTGTGGTTATCCTCTCACTTCGAACTAAACGGCAATTCCGGGAGGGTATCACCGCTAGTTGTTCTAATTACCGCCTGAACCAGTCATA
# 144->CATGTAGTCTTTCCAGTCGGCCGTTGAAAGAGGTGCACATGACATATGAGTCATGAGGTGCAGTGAATCAATGGAAAGGTGAGGGGACCACAACTTACAGTGCACTACCACTCTCCGCAAGTGTAGCACAGGTAAGTTATCGTATCGTCTCACTCT
# 144->TACACTAGTGTATTGGTGATTCCTATGAGAGTAGTAAAATTGCTCCGATTATTGGACCACGCTAGACAGCGTACCAACCGTCAACCGGCAGGATCTCAAAGTGTCGGAAGCGGTTCAAGATCACGGTCATCGCTAGTTGGTGGGGGTGACGATTTG
# 145->GCTCAGGCCTTCACGGGCATGCGAAGGGGCTCCATTGCTCCATGAGGCGTTTTAAGCGGTGTTGGAGCTCTGTTCATCAATTCGTTGTACCGAAAACCCTGTCTACATCAATATTTAGTGTAAACCTTCCACCCCACGGTCGTGCTGGTGAGCAGT
# 145->GTAAGGGGGTGGGCGAGGCAATCGTGGACGTTCTTGTAACTCGTTGCCAGACACCGGTCTATCGTGGCCCTTCAGTGTGGAGAATATCGATGTTTGACCGCTGTGGTACGCTTGTAGGTTCGGGGCGGGGGTGATCAAGTCTGGTACAGTCTTGAA
# 146->ATCACGCTAAGTTGGGAGAATAGCACCTGTGCAGCTAAAACATTTATGCTGTGGATAGCTGCCCGCACGTCCGACAAGACACATTTATGGCGCGAGTACTCGTCGCTGGTCATATTGCTGTTCCAGTATTGCTGAGTAGGAACCAACGTTTCACTA
# 146->AAACCCTCGCCGTATACTGCTAGAGCCAGTGGCTCGTCGATTCCTAGTGTTGCGATACTGATCAGCTTTTCCATCGGAGGGGGAGCCTGTTCTACGCGATCGGGTCATTTGGTTCCGGGGGGCAAAGCACGGTAAATGCGCTGGCCATATATCGGT
# 147->GCTCCTGGCTCCAGACTAAGTGGTTGCCCTGTCAGGGGGACTGAGAAAGACAACGCGCCCGAAAACCTGCTATCTCTCACCGCTTAACGAGCTTGAGGACCACGCGCACCGAATCTCTATACGCTGCGAGTAATACGCTAGTCGAAGCAAAACATT
# 147->CTCCCAGTCAATTTGTCGTTGCTTTAATTCGCGCTCGTCCATTCGCATCGACTTCTACGATTCCGGCGACGTCCCACTCCCACAGAGGGAAGATTAAGAGTTATAGCTCACTCGATATATTTATCGAAAGAAAGGGCTGTCGAGCCTAAGGGTAAC
# 148->AGCTTAGAACCTCTCCGAATGTACCGTCTAGATTTTTTATACCGAAGTACTCGTCTGAAACGCCTCACAAGTCGTTCACAGGCATAAGCTTCTCACGAGCATTGAAATGTCATACTGTGGCTTCTATGTGAATCGTTCGTTGACCCGAGATGCCCC
# 148->CGGGAAATTATGCAGATCACGTCAAACCATGACCTAGACCGGTTGTCCGCGACACGCGCCAGTGGATCCCGTTCCACTATAACATCGCCTTCGACAGAAGTAACCCGCCGGGTAGACCTCAGTCCCAGTCGGCGATTGTCCTTGTTGCTCCACGGG
# 149->GCCAGATTTAGCTCGGGGATCACTATGACCTTAGCGTGCACGAACGATGCTCGACCTGATGTTCAAGACCGTCAGAACTCTCACGTCACGAGATGCCGGGTCGGGTTCGCAGTGGCGCTATAGGCGATCAGCTAAGCCTTCGGCAGTTACGCTCGT
# 149->ACGGTAGATTGTACTCTTCCACTGACCTCCGTAGTTGTATGTTACGCCCGTGATTCCGCTTGGCATTAACGAGGTAACAAGTTTTAGAACTTGGCGCAGAAAGAATAAAAAAGGCTCCCACTGGGTAGTTGGGTAAAACAGTGGACCATCTTCAAA
# 150->GTGCGATCACGTTGTACCGGCCTCCTGGAGCGCATACAGAGTCATACTGCCCTCGTCTCTCCCTGTGGAACGGCGGGAAATACTTATCTCGCAAACGACTATTGCACCCCAGAGATGCTGACGACTAAATCGAGGCTGAATGAGGTAAATATGATC
# 150->TCATGCTTACACAGAGTACCAGTACACACTGCCCTTAGGCTACAATGCCTACTGATGTTTCCGGTTGGAAAGCGCTTGGACAGCGAGTTGAAGACTATCTTTTATGAATTGCACTCGTCTCCGTCAGAGAATGAGGCTCCATACAATGGCCGGGCA
# 151->GGGCGCTGCCTGAGGTAAAAATCTTATGCCGCTAGAGCCCACTGCTCCTCTAGCGACGCTGCGAGTACTAATCACGCGTCGGCATGGGTTGACCGTCTGGGTATTAAGGAAGAAACTCTCAGAAGATGTTAACACATGCGTTTACGCGTGAAGCCT
# 151->TTATGTGGAGCGAATGGTTCGCGAAATCTCGTTCTTTCATTCCCGGCGTAGCTCCACTCCTTCAGTTCAAAAAGCTTTGTGTCCCAGACCAGATCTTCTCTCTAGGACCCCACCAGCTTTCGATCGGTAGATGGTCGCACCGCACTGGTAACCGTC
# 152->TTTCTAGGCGGCCGGTGCGTGCATCAGGTTCTAACCAAGGCAATGCGCGAGTCTGCTGTAGGAAGAGAAAAGCGTTGTACTGTCCTGAGGGCCTATTACGCCAACAACTAACTTAGACCTCGGACGCTGGTGTCAGGACGTATTGGTCCCCCGCAA
# 152->GGATAACTGCAGGGGGATTCACTGCACCACCGCGGACGTCATCAGCGAGTCGAATCGCAATGTGGGAACTGCGGGCAGGCACCGAGACTACAAAGTTGACTTGGGGACATGTAGCGCGTGTAGCCAAAATTCATCGCGCATGTTCCTCTCCATGCC
# 153->CTTCCGAGCCCAGGACTGGTAATGACCAGACTACCTCCGGTCATGACTTCCTAGCAGTACGGTCTGCGAAGCTACAAATCTCATTTGCCAGGCCACTACCGGCCCTCAAGCGTTCCGACGAAAGACAAACGCTTACTATGGTGCCAGCTCTAGCAC
# 153->GGTACACGGAGAAGCGCGGAGCTTAGCGAAAACGACGAGTGTTAATTTGTCTAACACTATCCGTGCCCGGAGTCGTTGGACGATGGTGCAAAACGTGACGGGTTACCCGTCCTTGCTCTATGGCACAAAATAGCACTCACAGTACTAGTCTAGTAT
# 154->GATAATTTGTCAGAAGGTTGTCCACGCTACTGAGCTTGAATTGAGACTGTTGTATGGAAGTCATACGTGCGCGGAAGTCAAACCTCGTTCCGAAGCTACAAATAAGACGCATACGAGAGGTAATATCCCTAAGCTTCGCCGAACCCGCACTAAAGG
# 154->CTAAGAGGTGTCGAATCCAAAAGTTTGGCACCGGCGTTCTCAGCAACGACGTGCAAGAAACCAGATCCACGGTTGGAATCATCCCGGCAACGCATCAACATTGGCACGTTACCATTGCCGCCAGTGCCACAGTTGGGGGCGAGCCCGCAGTATCTC
# 155->CAGGACTGTTTCGCTCCCTTGGTAGGTCAGACTCAACTTATGCCTACTTTCAATAATTCGCGGTCCGCCATGGGGTTATGTACGATCCACTCCTACTGGAGGCTCGAAAAATTAGGCAACGCACTCTAAGACTTGTAAGACATCCTGCTAGCCCCG
# 155->CCGCAGGCTCTCGCCTCCGTTCGGGGGTCGCGGTCCCTCGGACTCATGGATTGCCGACTGATACGGCACGATTGGCCCGTTTAAGTCTCAAGGTTCGGTTCCAACAGGTCCGCAAGGGTGGCAATCACCCCGGCGTGCCCTGATCAAGTAGCATTT
# 156->TTAGTTGTGTTGTGATCTTTAAAGAGCATGGCAGGTGCGGGTTATACCAGGCAGCGAGTATTCTGACGGTGGCCAGCTTCTTCTGAAGTACAAAACTCGTGAACTACTCAACTTCCTCAACATTGGTGCATCGGGTTTCCAAGTAAAGTCCCTAAT
# 156->AAAGCTGGTCCTACAGTGAACACGGGCTATGTTTAATGGAGCGTGGTCCGTGCAAGAAACAGCGAACGTTACGTGCTTGCCTCATACCTACCATCGTGCTATGGGCGGTGTGATTGTGCCTACTTCTCTACGGTACTAGCTATGCGCAACACAGTG
# 157->TACTTCGAAACGCGTTGGATAGGGCCCTGAATCCTTCCGCGCTAGTGGAGTGCGTTCAAGCCCGGCCCCACTTACAATGCTCGGGGGTACGGTATACTGTGTATTAGTGAACATGGGGAATCCATCCACATAGCCCGCGACACAATACGCTTTCCA
# 157->CAGCGCACGCTTAAATAGTCGTCAATGTAGCAATCAGCAAATTGCGCCAATAGCGTCACAATGGGTGGCCCGATCACTGCCTTTGGGACATTGACTAAGACGTGTGCCATTAGGGGTAGCAGTTGAGTAGCCAACAAGGGCATGTGAGCGATATAT
# 158->CTGACGCGTCGTCGTGCCAGCAATCGATCGACCCGGTCAGACCATCTGGTCTAAGGTAGGAAAAATAGATGAAGGTTCACTCCATGAGGGCTAGCCATCAGGAATCTTAACTCAGAACTTACGGAGGTGACATGTCCAGGGGTCCATAAACGCACT
# 158->CACCATTCCGGGGACGCTTACCAATCATCTTATTGGTGTTCTTGAGAGTCGCATATCGGGGGTACCTGCTCACTTGGTTCGAGATAGCTAGGTGCGAACACCCCAAGATTCGCGGTACGCAAGTAAGAGGTCGTGGCTCAGGTGGGTCTCAGTAAC
# 159->GCAGTACAGGATCACTTAGAAGCGGGTAGTACCGACAAGCGGTCGCCTTAGCATGATGTGCCCAATACAAGTGTCAAAGTTGTATGTGCTCCAGTGGGCTCATATTTCTACTTACTCAGGTATGTTAAATCCGCTTGTCAGATGCAGAACGGCAGG
# 159->ACCGAACGTCTTGTATCGCCGGTCATGTCGCGTCCACAGGTATCCACTGCGCAGGCGCCGATTTGTTTTAGTTCTGGGGAGCCAACTGACGCCGGTCGCGAGTGTGTCTAATTCGTGGTTAGTGACCTCGAGCTACAGGTTGGTCCGCTTATGGGA
# 160->TAGCCATCAATCATATAGGGGCTCAAATGGTCCAACTCTGGGAAATAGCTATAATGACGGATGATAAGATTGAGACACGTGGCAACCCCTGGCTCTCGCACTGGCGCTGGGTTAGTTTCCGAGTAAGCGGTCTACGAGCAGAAGCTAAATCCATAA
# 160->ATGCCGATGTATAGCAAGTTGGACGGCTTTTAGTCGGAAACGTCGTTCGTTATTCAAGCGTGAAGCGGAGGATCACGGGACCCATGTTTCCGGTCCAGACTCTATGGCGAAATACAGGAGGAACGCTGAGGGCAATCGTTCGATCCACTGGTCTAC
# 161->ATATAATCGTGGCGGATATTAACAGTACGAACCCTGCTGCGGGCTACCGGTTGTTGCTTCTCAACAATTGACCAAAATATACGCTATGAGGTGGCTCTATCTGAACACCGCGAGTCGCCTGCCTCTTAATATGGGTGGTGCAGATGTGCTCAACGA
# 161->CCGGATTGTATATTGCCCACATCGGCCTACAGTGCCCAGGATTCTAGTTTCAAGTATTGCCGACCTTTGTATGACTCCCTGTGCCAGTGTTAGTTAGTCTAGAGCACGCGCCCACGGGGAGCTCCAATTGTACTCTCAATCGGACATGTCGAGCTT
# 162->CCTATACCTCGCATAGCCGACATGAGCAGATCTGGTGGAACTCGAGACGCCACACATGGCCGAAGATAGGGGCGAGAATCAGCCGAAAACCGACTAAGTCGACCGGGGCGCGCCACCCACGCTCTACATCCAAGCTGCTTGGTCATTGTGGGCCCC
# 162->GAGAGGACGGGACTCATCACTCATATTAAACGGTCAAAATCAGGCGGCGGGACGGAACTATAGGGGGTAAGCGAGATAAATTCATCTAGATCTAGGTAGAGACGGGATTGAGACCCGCCGTATGAATCATCGTGTTCGTTATGCCGTTAATTTGAC
# 163->AATACGCACGGATGTACGAGAGACCCCGGTATCATTGCCCGTGCATAAGGACTCATTTCATGCACCCCAGCATTCTGTAAGATACACCGCCTGTCCAAGGTGCGTTTATTCGATGCTCTCCACGCTCGCGTTCGCAGGATGGTCGAGTATCCTGGT
# 163->GCGTCGGATGCGCAAACCCTGCCAAAGACTCAGATACGATGTTAGACAGTGAAGCTGGAACCGGGGGAATTCCCGATCCACTCAGGCTAGCCCTGAACACCACAACGCTATCATGATATACTTTTGATTGTTAGCTGTAATGTCTTCTGTGAGGCC
# 164->AAAGTGAACGGATGTGAGCTGTGACAGATGGCTTTTTGTCTGGCGTTGATTTTAGCTCCCGGTTGTTGCCCTGTTATGGTCCCATGGAAAATTACGTACGCATCCAAGAAATGGGAACCCCCGTACCGTCCGGGTGTATGGTTTGCGCGCCAGCTT
# 164->GGATCTCGCCGGGCGCACAGAGGGAACGGATCCGAAAATGCGAAACCGCACCCCAGTAACGATCTACTGAAAAAGTATAGACTAGTTTTTGTCCGAGGCTCGCAAGCTCTACATGCTGTTTAGCCCCGACCTGGTACTGGTAGGTGATTCTGTGCC
# 165->AGGCACGTTTTGGTGCGATTTGCGCACGGTAACACTCACTGGAGCAAATCATGCCCAGCCTTACTCCACCAACTCGCATCGGCCAAGCGGCCCCAGAGACGGATGAAACGGGGGATCGCTTCAAAATAAAGACCACATTTGTACCCGTGCACGTTG
# 165->AAGGCTAGATCATCGGCACTAACAAGTACACTACCTGAATGATGCTTACCCCTGGGCCAAAAGAAATGATCTTGTATATAACACGACGTCGCAATCCCTGGTGGCGACCTGCTACTGCTCAGGACAGTCTGGAATTTGCCAGGTCGAGCCTTCCGT
# 166->CCGTCAACAACGTCGCAATAGTTGACTCCCAGGTTTGGGGCTTTGGAGACGAGGAGAGTGTAAGTTAGGCGCGTCTCCCGAATAGACTGTCAGGCACTATAATTGTGGAAGCTTTCTGCTTATGCCAGAGGCCGTGCGTACGACAGAAGCGCATGT
# 166->GGCCCCTGTGAATCTAAAATTTAGGCTGGCGTGGAACAACGATTGGGGTAACTCTACGGCGGTATGCGCTGACAAAGTTTCTCGTCCTCTATGACATAGGTTGTTAGTAAGTCTGGTATATGAGTACGGTCTCCGGGTTCCTGAACGGATTCCGCG
# 167->AACATTATGTGGGTTTTCAGCTATTAGCGCATAGCTCTCGCCGCAGGATGCCTTACCGTGAAAATAGCCTCATATCCAAACGCCGACTTGTCGTTACGAGTTGCTCGCTCGACCGACGGGTAACGGTGAATTAGCGATACGTGAGGCCCAATGTAC
# 167->TCTTCTGTACTAGGGGTTATCGGGGACACTCACCTTAGCAATCCGCTGTATGTCCAACGGTAGATGAGGCCTCTTATGGCTGCCGACTTGGGTTTCCCTAACTAAGAACAGCTTCGCAGACATCCGCACTGAATGCTCGGTGACAGATAAAGATAA
# 168->GTCGAAAACGCTTGTGATAGGGATTTCGTGCGATGAGTTCTCTGTCGGCTCTGCATAGCTAGGGTAGACTTTTGAAGAAGACATGAGGGATCGGATACATCGAGTAGGTTAGGCTGCACCGATGGTATGCCGTAACAATCTGGACACTAATGGGCG
# 168->CACTCCTACCTCTAAGGGATGCTATTTTGCGTGCAACTCTTAGTTTCCTCGAACAACTGCCGCATAAGCCGTTAACAGTTAATTGGAACATCGACTTCCACGTGCTACGGTACATCTTTAAGGTTTGCTCTACCCTAATGGAACAGATATCGAAGT
# 169->TTTCTGAGTACTACGCTCAACGGCGGAAGGTAAACATGCCGCAGTTTTATAATAATGTTGTTCTAGGAAAACTCTCGGGCTCTGTAAGGTCCCGATAGGTGCGTCCATTCTAACCCGGGATAAGCGGGCGAAATCAGAGAAATCTCGGGGACAGGG
# 169->TTAGGTACGAAATCAGCGCATATGTTGAATGGTGACAATTCATCTCGATGGCTACCAATATATATATCGATTCTTACTTCACACGCTCTCGCCGCGTACATCTTCCATTGTGCTGTCCGTACGATGCTTTGCTCCTATGCGTAAGGCTATCGCAGC
# 170->TAAGGTATTTGGTTATAACAAGGAAACACTTTACAGGTAGGTTTCACGTTAAACCCTTCCCAAGCCAGGGAATAGATGCAATTACCCTCGCACAGGATTAGCAGTTAAAGCAGGATCTTCGCGAGTTAGTTTGGGATATTTGCATGAGACGGCGGG
# 170->CCTTCAACTAATATGTACAGCGCCTAATTGAATGCTGGGTTAAAGATTGTTAATTTAATACACCATTACGATTGGAAGAAGACCGCGTGTAACACACCGTAGTCCACCATGAGAAAGAGCGACATGTATGCTACTGAAATAAGCGGCTACTACGTC
# 171->ACGACAAATCTGCTCCCGGAGCATGCCACTATTCCAGACCGTAGCCGTCAGTCAAGAGTGTAATCACACACCACACGCGTGTAGATTGGGCAGACCCTACTCGCACGATGTTCGGCCTTGGGTCGTGTGGCCCGGATTTATCTCTCATAGTTCCAG
# 171->ACCAGAGCGGCTCAGGTAGAGTCTTGCCTCTCCTAAGTTGAGTATACCGACAGCCCCAGATCGACCTCGGCACGTGTGTGGCCAGTCTGAAGGCCGCGCGAATGAGACGTTACGAAGGTAAGTCACGTAAGTCCAGGTGGTATCCTTAGAATTTAA
# 172->TCCTTTTTTCGTAGCAAGCGGGGAATAGGACATTGCGCGTCTGCATGAGCCTCACGTGCTTAGAGTTCTTTCAATTAATGTGAGCTCGTGCCAGTATGAACCAACAACCAAACCTAGCTCAGAGGGTAAGAGTAGCGGTCTCCAAATTACGCAAGT
# 172->ACAACCCTTTCGGCCAAACTTCAGCATTGCAGCAGCGTGCGCAACGGTTGTTACTTTGTGATAGTACTGGCGGCATTTACGGCCCATATTCTGGATTCTTCTACTACTAGGACATTGGTTTTTACAGATGTCTACGTGACGCAGGCAGAGTTATGC
# 173->TACGTGGCCGAACTATGGGGAATAAGAGACCAGTAGTCGCGGTCCCCGCGCCGACAAGACAATACACCCAGCGGCCTTCAGAACTTGGATATGCGAGTACTAGAACTGGGGACATAGGGACGCCGCGGCCCGGTTTGCCGGGAGGCATGCCTCATA
# 173->GCCAGACATCACACACCAACGAAGTTTCCATAAGCCGCGATTTGGCTACGATAGTTAGTAACGCGTAAATAACTTATAGGTGGTGCGACACAAAGCGGGTGGAGGAACCATGGAGTATAGGGGGGGGTGCCACGCCCGTGGCCACTCCACGGTGTG
# 174->AATCCAACGGGATTGAAGCAACCGGCTATACTGCGCCTTTAGTGGGTACACTCGTACATCCGTTACCACACGAGCTGGTCTGATCTGTTACTCAACAATGCACGACGGCGTGTGAAGCACTCTAACCGCCGAGGTTCCAAGTAGTACGTAAGAATG
# 174->TTGCGGTTTGAAAATTGTGTGGGATGAGAGCGCATTAACCTGTACGTCCTGAAAAGACTTCATTAAGTGGAGCAGTGCGATTGGATGAGAGATCGGATGCTACCATATTACAAGATCAGCCGCACGTCGGGAGAGATAGGTGTTTTGACAGAAAAC
# 175->TATGGATCGAAGCAGTCTGGATATTGTCAGTACCGGAAGGGCACTGAATGTCTTGGACATGAGCAATCCACCTTGCTGTCGGTCCTCGACATCGGACCCGGCCCCCCTTGAACGCCGCTATTCGATTTTCCAGACAAAACTTCCCTACGGGAGATG
# 175->AGTCAGTCGCCAGATCAATCTCGCATCATATGCCCGCGGTTCTTGCAGTCACGACTGACTGCTGGGTACAACAAACGACACCTTACGATGGGCCTCGATAGCTGTCTAACCGCTGCCGCCTCCCGGAAAGAGGCCTTCCTCGGAGAGCATCGTTGG
# 176->GGGTCATCGCTGATGTCAACGTCGCGTCCGTTAGTGTGTAACAGCATTCCTACACGTCCAGGCCGAGCAACTTTCGAGTGCAATCGTTCGACAGATCACGACGCATGGATCACGAAATGCCTAAACAGTTCACGAATATTGACAATTTAGATGAGG
# 176->ATCTATATTCGTCCTTACTCCCCAGTTTGAACAGAAGTTATGCGTCGGAGAACACCCCCGCGGCTGATCCAAGCGGTCTACCCATTCGTAGTTAGTAGGATGCGGGGCGGAGCCTGATATACAGTCTCGTCTAACCTGCTGATACCCTATAACAGG
# 177->GCTTAGGTAACCTGCATCAGTTCACACCGTTAGGCGGCAGGCAGACAGGGCGACTGCTATACGTATATGTTGCCTATGACCAGGTTGACGACGTCGAGGACCGGGAATAGACCACACACGCGTGGCGGAGTATGTTTAACGGTTTAGTGGGAGAAC
# 177->GCTTCAAGGAGCTACGCGAGAGCGGGTAGTGTAGGCGACAATTCTTAAATTCTCTAACTAAGGTAATTTGGCCGCTTTCTCCGTTTAGTGGACTCTTCTCTAGCTGCATTGTTGGCCACACCGCCGCATAACACCGCGTCCCTACACCGGCCTTGT
# 178->TATGCTGCTGCGACATTCTCAGCTCATCGATTACCGTTTGATCAATCCGGGCCAACAGAAGGGTCGGCTACCAAAACAGGCGCACTCGTGATCAGCGCATAACCCAGGTAAGTGTTCAGACGAGAAATACGCACAGTGATGGTACCTGAAGTTCGG
# 178->TTCCAGCTTTCGACGGGCCAGCTTTCTCCCAAAGCGATTTGAGCATAATGCGACCGGCCTGACCACTTATGCTAAATACGTCCTTGGATGGTTATATGAACATACCAAGCTTTCAGTACGAGGCACACAGCCTCATGATATTAGCTTACCTATGTG
# 179->GTTAGTGGCTTGCACATTATGTACGACTCAAGAGTGGCGCTCTATCGCATTTGCGTTTTACCATAGGGCGGGCGCCCGGCTAATTGGTGGCGGGCGATGCATTTGTTTTAGACACTAATCTATATAAAATCGAACATGAGCAGCAATTTCGGCGAA
# 179->GACACACCGTTAGCGTAGAGGTTGCGGCCCAAAGAATCGCAGACGCTCTGAGTCTTGAACTGAAACGGTCTTCTTCTGACTAGGCCACTGTGAGGTCGTCCTATCTCTGGAAGGGAATATTTTGAGGACCTACTGTGCTTGTGTTACGTCCATCTT
# 180->CTGTGCATAGTCCTTGCGAAAACAGCCCATTTATGATGTCTAGGGCGGGAAATATTCTCTCTGTCGGGGGGCGAGATACGCGTTAAGTGGCGTAGCTAATCACAGGCGAACTGCGGGTGCAAAGGCGCCCATGGTATCAGTCATTTCGCGCGGGGA
# 180->GACATATCTGTTCCCTTTTTTCCTGGTGGACCGGTACAGGCGCTTGAGCCTGTGGCTATCAAAGGGCCGTTTCCGCGGGGAGAGCACCCGTCTACTTAGGTACGACCCCTCGGTGTTGGAAGAATGGTTACTCACGAGGAATTGGCAGCCTTCTCA
# 181->GTCTGGTTCGATATCTTGCACGTGCTCTAAGTATAACTAGTTATAACGAACAATTATTCCTGTGTAAGGCCGATCGAGAATTGGTAGTGTACCCGCTTTCCATCGCTTGGACAACCGATATGTTAAGAATAACTGAATAGATACGTCAGCCTTTAG
# 181->GGCGGCATACGAGCTCTCGTTTTCGGGGAACGACACTACTCTCACGATCGCGATTTAGGACCTAACAACCGTTAACGGAGGGGCTAGAGAATTCCCCTGCACTGAGATATCCATGCGATAACGGACTGTAACGGAGAAAGCGAAATCAGTCAAGAG
# 182->CATTTTTAGCTGAACTGGAACCTCTACGTCCCTACAGACGGCCTAACCCGGTCTGGGGATTCTCCTTAACCACCGCTCTGTGGGAAACTCTGGGGCAACAGACATGTGTTAATGAGGACACGGACCAATTAGCAGATTGCACAGAACACGCCGTTC
# 182->TATCCGATACGTGTGGAGTAAAGATGTGCTGCCACAATGCATGGGTGCATCATCACCCTAGCACTGCACGCCGCGCACGCAATGTACACCTACATAATGTCGAACCCATTTCCTGTTGCATGCTCTAGACGAGTGCGCCCAGAGACCATACCGGCA
# 183->CGGAAAGTGAATTCGCACGGAGAGTGGCGATTGAGGCATGCCCCTCGTTTTGCGCATTACAGTCAGATAGCGTGGTATCCATGGCTCAATGTGTGATCCGTTATAGCACCCTACGGCGTTGCTATATTTTTAACCGCTGCCGTTGTAAGGCGTGGG
# 183->CAACCTTCCAGATAACTGTCCTCAAGGATACCGAAAAGTGATTCCGCACCGCTCTCCTCGACACCAATCGCTAGTGAGGTGAGTTTGAAGCAATCTAGTCATCGAGTGTAGACTCCAGCTAAAAAATAAGGCTGGACTCGAGCATTTGCGATTAAA
# 184->TTAGCGCTTTTTTTTGGAACGACTATAAGTATAAATCCGTTTCCAGTGTAGATCGTGACTAAACGTAAAGCGAAAGTCGAAGCTCCTTGCCCTGCTATGCTAGCTTGCCCACTTCCGCCGTTTAGACCACATGCTAAGCACTCTTGTAGGATAATG
# 184->ACACCGCTCATAGGTAGGCAGCACTGATGAAATAGGTTGTCTCCTAGCAAAGTATCAACAGAAGTACAGACGGTCCTAAGCAAACATAAAGCCACTGATAGGCGGCCAATCACTACTCGCATGAGCTAATACTCTCCGTGCTCACCGGGTTCAAAA
# 185->GCTACCCGTCGGCTTGAGTGCAGCGTCCCTAAGCCGATCAGTACTCTCTTAATTTGATAAGCCTAGCGGTTAGGGTCCGAGCGAGAATCGACTCTGTCGTCCTGCTGAGACAGAAGATCACGTCATGTATCAACTAAGGTCCCGGTTTAACCATTA
# 185->AGGGTTGCCAGGTGCTTCCTGTTATCAAACTAGAGACTTACTAGGTCAGCCTAAGACTGGTAATATTCGTGCAGCACTCCGCCCGCAAAGTCCGAATGAGCCCCATAACATTCCCGCCAGACGTGGTCCTGCCTATATGTCTGTTTGTGCCGTGAC
# 186->CGCCTGCCGTAACTTATTGTACGCTCAAGTTGGGACTGTCTTCACTGAAAACAGCGCAGCGCTCCCCAGGAAGAAGGTCCCTGGAATTATATGGCACTCATTTACTTAGCTTGTATCGAGTCTAGCTAAAAGCGAGGTGACTGGAATTGTCACTGC
# 186->GTAACAGCGACAACCTACGCTCTGCTTCTCACCTAATAGATAAAGAAGGTATAAGCCTAGTGGATACGTAACGTAATCCGGGTTCCTGAAAAAACGTATGTCCAGCAGCGTGCCGAGCTGGATTATAAGCCGTTTGTCGTCCGCTCACGTTCAGCA
# 187->TGTGTCTACACAACTCCACTGCAAGTTTTGCTCTGACTTTCGCTGCCCCCGGATCTCACCCAAAGTCGGCAGATCTCATCGTGGAGTGGTCTATTAATGTCTTCGAACAGGTACTTAGTTCTCATTCCTCGTTCTGTGGGCATGACCAGGGGTGCG
# 187->TGTGTGCAGCTCCGAGTACTTGCATCTCAAGCTTTCGAAGTCTTTATTACGTTTCACCGCCCGTTCATCGCTGTTGCATCGCTGCGCGCTTAGTAAACGCACTGCATGGTGCCAGCCGTCGCTATATAACTGCTTGTTGGTCCTGGTCTGTCAACA
# 188->AGGGAGCAGAGTGGAGCGGAGGTAAACCATTCTGGGGAGATAATCGGGACGGCGTCAACCCTACGCTGGGATGCCGACATCTTCTAAGTCTGGCGGACTAAGTACCTCGGATTGGGGTTCAGGAAACAACGAGGCCGTTAAGAGAGATGGCTCGGC
# 188->GGACTGGCTCAAGCGTGACAACGAGCGCAAGGCAGTCAGGATTCATAAGAATTGAAAAATGAGCTACCACACGGCCTTGTCTATCTATGTCTGAGTAGGAGTGTTGGGTCAAGTAGATGAGGTTGATATGTCGATGACTTCACTCCACCAACGGTG
# 189->GGATAGACGTGCCAGTTATAATATCGAGAACCATGGACAGAAAGCGTAGGTCACGTTGTTCTTCTACGCCAAACCCTGGATCGCTAGACGCGCGGGGAATTAGCATATCGCAACATTTCCGGCGCTGGTATGACGAACATCTAACCATATACATAC
# 189->CACGCGATATACACTCAGGCCTAGCTGCTCCTTGCGGACCTAAGTGTACGTGGAGACGCTACCTCTTCTCAGAGATAGCGGACTAGCAGGACTATTGGGGCCCCACTGCCCTAGGTCGGTGCGTCGAAAATCCCGACTGTGCCGTCTTCCGACGGT
# 190->CGATCGCCCCCTTTCTACAGCAACGTTCGAATTGACAACCGGTTGGACATAAGCCGTGATGTTTACACAAACATCAGGGCGTCTCCCATTCTGTGGGTTCCGTTGGTGATGGAATGCTGATTAAGCCATAAAAACAATAATGCGAACGGGGCGTCA
# 190->CCGGCGATCATTGGTGTTATAAAAGCTTATGGCCTTGGGGCCCGTGATTAGTTTACAGAGAACCAACAGCCCTGTCTTTCCTACGCATGACAACCATGGGCCGGAGATGTGTCGCACGGTATGGGGGTACAACACACCCCCAGTGGTTCCGTTTGT
# 191->GACACTTGGGCAGAGGAACAATCTTACGCTCGGAATGTAAGCACCTAGTGAACTCTCGTGAAACCGGGTCATTATGCTCGCGCAGAGTTTGTTAGCAGAAGTTTACTGTCGGATGTAAGCAGAATGTCCAAACTAGTTTTATCGTCGTTCTATGAT
# 191->ACTGTTCACTTTAGTTTTAGCACTTGACAGCGCAAAACGTGTGTCGATTTTCGACCGCTCAATGTCATCCGGGGGCCCGTATGGCCACGCGCAGCCCGTTGTTTTACCACTGGTTCACGAGTGATCGGCGATGGATGAAACGTTGTTCGGCCGACC
# 192->128
# 192->132
# 193->181
# 193->178
# 194->138
# 194->169
# 195->145
# 195->189
# 196->180
# 196->147
# 197->163
# 197->152
# 198->185
# 198->151
# 199->144
# 199->191
# 200->146
# 200->165
# 201->170
# 201->142
# 202->140
# 202->188
# 203->157
# 203->153
# 204->186
# 204->156
# 205->161
# 205->173
# 206->141
# 206->134
# 207->143
# 207->150
# 208->190
# 208->160
# 209->129
# 209->159
# 210->166
# 210->130
# 211->174
# 211->135
# 212->136
# 212->175
# 213->177
# 213->155
# 214->148
# 214->172
# 215->168
# 215->158
# 216->176
# 216->149
# 217->182
# 217->137
# 218->162
# 218->139
# 219->171
# 219->183
# 220->164
# 220->133
# 221->154
# 221->187
# 222->131
# 222->179
# 223->167
# 223->184
# 224->214
# 224->216
# 225->206
# 225->194
# 226->211
# 226->193
# 227->219
# 227->208
# 228->215
# 228->221
# 229->199
# 229->202
# 230->212
# 230->218
# 231->223
# 231->200
# 232->192
# 232->210
# 233->213
# 233->222
# 234->201
# 234->207
# 235->204
# 235->198
# 236->203
# 236->197
# 237->209
# 237->195
# 238->217
# 238->196
# 239->205
# 239->220
# 240->236
# 240->234
# 241->238
# 241->232
# 242->228
# 242->226
# 243->239
# 243->227
# 244->237
# 244->233
# 245->235
# 245->230
# 246->229
# 246->225
# 247->224
# 247->231
# 248->243
# 248->241
# 249->244
# 249->245
# 250->242
# 250->246
# 251->240
# 251->247
# 252->251
# 252->248
# 253->250
# 253->249
# 254->253
# 254->252"""
#     solve_full_tree(string)
#     string ="""8->C
# 8->C
# 9->A
# 9->C
# 10->G
# 10->G
# 11->T
# 11->C
# 12->8
# 12->9
# 13->10
# 13->11
# 14->12
# 14->13"""
#     solve_small_parsimony(8, string)

    #################################################
    #                    UNROOTED                   #
    #################################################
    string = """TCGGCCAA->4
4->TCGGCCAA
CCTGGCTG->4
4->CCTGGCTG
CACAGGAT->5
5->CACAGGAT
TGAGTACC->5
5->TGAGTACC
4->5
5->4""".split("\n")
    string = '\n'.join([s for i, s in enumerate(string) if i % 2 == 0])
    # solve_full_tree(string)

    string = """CGATATTATTTTCTAATGTAATCGTTTTTGTT->32
32->CGATATTATTTTCTAATGTAATCGTTTTTGTT
GCAGTTAAGTCCTCGTAGGTCATTCTTGCTCT->32
32->GCAGTTAAGTCCTCGTAGGTCATTCTTGCTCT
CATCAAAGCTAACTTCCAGATTCGAAGTGACC->33
33->CATCAAAGCTAACTTCCAGATTCGAAGTGACC
GCAAGTGCGAGGATAATAATCATGCCTGGGGG->33
33->GCAAGTGCGAGGATAATAATCATGCCTGGGGG
GAAGGGCGATACTTACTAGTGCGAAAGCGGTT->34
34->GAAGGGCGATACTTACTAGTGCGAAAGCGGTT
CAGCAACAGTCAAATTCCTGATCTCAGACCGT->34
34->CAGCAACAGTCAAATTCCTGATCTCAGACCGT
GAGAAGGTCTCCGCACCGGTGGGTGCTCGCGA->35
35->GAGAAGGTCTCCGCACCGGTGGGTGCTCGCGA
TCCTGATGTACATTTCCAAAGCGCAAAAGCCA->35
35->TCCTGATGTACATTTCCAAAGCGCAAAAGCCA
CATTTCCAGCTCGAGGAGTCTCCGCAATTTAC->36
36->CATTTCCAGCTCGAGGAGTCTCCGCAATTTAC
ACGAACTCCTGGGTATCCAAGATGCAATCCCA->36
36->ACGAACTCCTGGGTATCCAAGATGCAATCCCA
GGTCTCAATTGAAGGCCCCTTCACTTTTCATA->37
37->GGTCTCAATTGAAGGCCCCTTCACTTTTCATA
TTTGGGATGAGTTTATCACCGATTATACATTT->37
37->TTTGGGATGAGTTTATCACCGATTATACATTT
TCTGCGAGACGGCCCTTCATACCGTAAAGATA->38
38->TCTGCGAGACGGCCCTTCATACCGTAAAGATA
AGGCTAGCAAAACATACATCTCCGCTTACTTT->38
38->AGGCTAGCAAAACATACATCTCCGCTTACTTT
TTTTTGAGGCCCTATATAGCCTGTGGTAGCCC->39
39->TTTTTGAGGCCCTATATAGCCTGTGGTAGCCC
CCCAAGGTCCCTCCAAGTGGGAGCTTCGCAGC->39
39->CCCAAGGTCCCTCCAAGTGGGAGCTTCGCAGC
CCGAACCTTAGATTCTACCCCTGCGACTTCCG->40
40->CCGAACCTTAGATTCTACCCCTGCGACTTCCG
ACGGGTTCGTTGGTACGCGCTTGAGTACTCGT->40
40->ACGGGTTCGTTGGTACGCGCTTGAGTACTCGT
GACTCGCAGCTGAGCCCTCAATCCTAATAGCT->41
41->GACTCGCAGCTGAGCCCTCAATCCTAATAGCT
CCCAATATCATCGATATCCCGATCGGTTTTTG->41
41->CCCAATATCATCGATATCCCGATCGGTTTTTG
TTGGTCCGGTAGCTTCTGATTTAACCACTTGA->42
42->TTGGTCCGGTAGCTTCTGATTTAACCACTTGA
CAGCTGCTCGGGCCAATGACTTATTGGTGAAC->42
42->CAGCTGCTCGGGCCAATGACTTATTGGTGAAC
AGCCGAGGGTTTTCTGAGAAGCTTAGAGGCGC->43
43->AGCCGAGGGTTTTCTGAGAAGCTTAGAGGCGC
ATTATCACTCATTTCGCAACGGTGACGCAGAG->43
43->ATTATCACTCATTTCGCAACGGTGACGCAGAG
AAACCATAATTTAGCCGCCTGCGATAGGGCAT->44
44->AAACCATAATTTAGCCGCCTGCGATAGGGCAT
CAGTCCGGCACGTGGGGGGGATGACAGGTCAG->44
44->CAGTCCGGCACGTGGGGGGGATGACAGGTCAG
TACGTCCAAAGAATCCCAATCCACTGGCATCT->45
45->TACGTCCAAAGAATCCCAATCCACTGGCATCT
AGAAACCTAATAGTTAGGGCTCTAGTTGCACT->45
45->AGAAACCTAATAGTTAGGGCTCTAGTTGCACT
CTCGTCTAGGATTTATCATGTCCCGAAATGGA->46
46->CTCGTCTAGGATTTATCATGTCCCGAAATGGA
TACTGAGGAGCGTCTCCACGCACGCAGAATGC->46
46->TACTGAGGAGCGTCTCCACGCACGCAGAATGC
AAGCCGTCCGTCCGGTCTTGTTAGTGCTCAGG->47
47->AAGCCGTCCGTCCGGTCTTGTTAGTGCTCAGG
GTAAGGGAGGATGACTTTTGCAAAACGTACTC->47
47->GTAAGGGAGGATGACTTTTGCAAAACGTACTC
43->48
48->43
32->48
48->32
39->49
49->39
46->49
49->46
45->50
50->45
33->50
50->33
40->51
51->40
50->51
51->50
38->52
52->38
35->52
52->35
47->53
53->47
37->53
53->37
48->54
54->48
52->54
54->52
49->55
55->49
53->55
55->53
51->56
56->51
55->56
56->55
34->57
57->34
41->57
57->41
44->58
58->44
36->58
58->36
56->59
59->56
58->59
59->58
57->60
60->57
59->60
60->59
42->61
61->42
54->61
61->54
60->61
61->60""".split("\n")
    string = '\n'.join([s for i, s in enumerate(string) if i % 2 == 0])

    # solve_full_tree(string)


    string = """CGGTTAGCACATGGTCACCTCAATAGAGCCGGTG->32
32->CGGTTAGCACATGGTCACCTCAATAGAGCCGGTG
GCCCTGGGGCGGCTGAGACGGAATGGAAAGCACT->32
32->GCCCTGGGGCGGCTGAGACGGAATGGAAAGCACT
CGCGCGCACTTTGGATTGCCGAGTTCCCTAGTAT->33
33->CGCGCGCACTTTGGATTGCCGAGTTCCCTAGTAT
TCGGAGCCCGTGGACTCTTCGCACCGATAGGATG->33
33->TCGGAGCCCGTGGACTCTTCGCACCGATAGGATG
TCACAATGTGACGCGAGGCGAACATCGGATGCCC->34
34->TCACAATGTGACGCGAGGCGAACATCGGATGCCC
AGTATCCACTGTGTAAGTAAAAGACCGGCATATA->34
34->AGTATCCACTGTGTAAGTAAAAGACCGGCATATA
TAGACTCTAGGCGACCAGGTGGTCCTGGTTAACA->35
35->TAGACTCTAGGCGACCAGGTGGTCCTGGTTAACA
GCGAAAGGCAGCCAACCTTTTTAGACGGTAATCG->35
35->GCGAAAGGCAGCCAACCTTTTTAGACGGTAATCG
TAAATTTGTCGACAAGACGTCTGTTCCTGGTCAG->36
36->TAAATTTGTCGACAAGACGTCTGTTCCTGGTCAG
GTACGGTTAAATTGCATTACCCTCGATTCGCGTG->36
36->GTACGGTTAAATTGCATTACCCTCGATTCGCGTG
TCGTTTAGTCTTTTCTACGTGTGGTCTTACCATG->37
37->TCGTTTAGTCTTTTCTACGTGTGGTCTTACCATG
CCACTTAACTGTTGCCGACCTTAAGAGGCGACAG->37
37->CCACTTAACTGTTGCCGACCTTAAGAGGCGACAG
ACTGGCCAAGCATATTGAGTCAAATTACCCGAAA->38
38->ACTGGCCAAGCATATTGAGTCAAATTACCCGAAA
AGGGTAGCTTCCTCGTTGGGTGAGCCTGAAGGAG->38
38->AGGGTAGCTTCCTCGTTGGGTGAGCCTGAAGGAG
GGTGTACCACTGAGCATCCTGCTGCTACTATCAT->39
39->GGTGTACCACTGAGCATCCTGCTGCTACTATCAT
GCGTCATTGGCCGTACAACCTTACTGATAACAGT->39
39->GCGTCATTGGCCGTACAACCTTACTGATAACAGT
ATACCCAATAGAACGTTATTGACTGGGACGATAG->40
40->ATACCCAATAGAACGTTATTGACTGGGACGATAG
TCCCAAACAACCGAGAACTCGATAGCTCATGCCA->40
40->TCCCAAACAACCGAGAACTCGATAGCTCATGCCA
AGACAAGTACTCTGTCAAGTTTGGGGACCAAAAT->41
41->AGACAAGTACTCTGTCAAGTTTGGGGACCAAAAT
CCCATTCGGATCAAGAAAAATGTCACTCCTATGT->41
41->CCCATTCGGATCAAGAAAAATGTCACTCCTATGT
CCCGTCTATACTACATAGCCGCAATTGTGCTCCA->42
42->CCCGTCTATACTACATAGCCGCAATTGTGCTCCA
CACTTGAGCCACGGGTTGTTATGTGATGGTGCGG->42
42->CACTTGAGCCACGGGTTGTTATGTGATGGTGCGG
ACCACAAGAGGGAGATTACGCTTTAGCGCTAAGC->43
43->ACCACAAGAGGGAGATTACGCTTTAGCGCTAAGC
CTGACGAGAGACTTGGCTAAGGCGGACCTAGAGC->43
43->CTGACGAGAGACTTGGCTAAGGCGGACCTAGAGC
GAACTTGTAGCGACGTCAGTTGGTTTACTATTCA->44
44->GAACTTGTAGCGACGTCAGTTGGTTTACTATTCA
ACTACGCAAATGTTACCCATATGCGGTTATCCTG->44
44->ACTACGCAAATGTTACCCATATGCGGTTATCCTG
GTGAGGCAAGCACATCTAAAGTCGATTTACTCCA->45
45->GTGAGGCAAGCACATCTAAAGTCGATTTACTCCA
TAAGATTTGCTGGGAGTCAGTACAAATAGAGCTA->45
45->TAAGATTTGCTGGGAGTCAGTACAAATAGAGCTA
TAAGCGGGGAGTGCTCGGCCCTATTGTAGTGAAC->46
46->TAAGCGGGGAGTGCTCGGCCCTATTGTAGTGAAC
ATTGGAAAGCATCGGGGCAGCCAAGGGGCTCGCG->46
46->ATTGGAAAGCATCGGGGCAGCCAAGGGGCTCGCG
CCGATAAATAGTGCAATGCAGTTTGGCCATGCAA->47
47->CCGATAAATAGTGCAATGCAGTTTGGCCATGCAA
CAATTCAAAGCAAGCAGCCCAGCGATAGCCTAAT->47
47->CAATTCAAAGCAAGCAGCCCAGCGATAGCCTAAT
36->48
48->36
42->48
48->42
41->49
49->41
45->49
49->45
48->50
50->48
39->50
50->39
46->51
51->46
44->51
51->44
37->52
52->37
32->52
52->32
47->53
53->47
50->53
53->50
40->54
54->40
53->54
54->53
35->55
55->35
51->55
55->51
38->56
56->38
33->56
56->33
54->57
57->54
52->57
57->52
43->58
58->43
34->58
58->34
56->59
59->56
49->59
59->49
59->60
60->59
55->60
60->55
57->61
61->57
58->61
61->58
60->61
61->60""".split("\n")
    string = '\n'.join([s for i, s in enumerate(string) if i % 2 == 0])

    solve_full_tree(string)