"""
@BY: Reem Alghamdi
@DATE: 11-09-2020
"""
from ch2.code.ch2_04 import d

if __name__ == "__main__":
    print(d("AAA", ["TTACCTTAAC", "GATATCTGTC", "ACGGCGTTCG", "CCCTAAAGAG", "CGTCAGAGGT"]))
    print(d("TAGGA",
            ['AAACCATTCCTCAGCATGCCAGAAAGACGGTCTATATCCTTGGCGCTTAGGCTTTGGCCAACATCGAGAAGGACGAACCCAGCTTGCCTTCCTGC',
             'AGGGTCAGTGCGCTAACACTTGCCAGTTCTTCTTATATGGTCGACAGCGCGGACGATCTTTAGAGTATGTCGGGTTGAATTCGCCCAAAGTGCGG',
             'TGTACACGCAGGATGGCAGGTAACAGGCTGCATCATCGCCGTTGTCGGATTGTCACGGGTGGCGGCTAGCGTACGATTGTAGAGGATGGAAGAAT',
             'CTATCGTTGCCGTTCCTTAGTACCCAGTCCTAAACACCTACGATACGCATCGAGGTAAAATATTTCGAAAGACCAGGAGTCTGCGGGTTCATCGT',
             'CAAAGTGCAGTCACCACCGCGCAGAACTGATTGACTGCCGTCCTCTGAGTTGTGAGGGTTCCGTCCCACTAATATAATGGTCCTACGGAAATTAT',
             'CTATCGCACAAGTTTACCTCAGTTAGTCACTGGAGTCACTTGCTGCGTATAACTTCGTGGGTTGACGATAACCGAAACGTACAGCGGCCTGGGCG',
             'TTTAAATTAGGACGTCTACAATCCTAACAAACTCACAACTGTAATTCTATCTAGGTCGTAGATACAGGCGATGTAACTGCACCGACTGTTCTTAG',
             'CGTGTTCGGACGTTGCACTTTACATGCAGTTTAGTCTGCCGGGCACATCCAGCGCGTCGCGTGTTTGCCTCCTATGTTGATGCAAAGTGAGAGTT',
             'TGAAACCTATACGGGATCACATTTGAAACCAAAGCGATAACTGTTTCACCTGGCGGCGTACTAAGGCATTCAAACAAGGAACAGAATACCCGTCT',
             'ATTGGCTCTGATTAGCCTCCGGTGGGTTAATCAGACACCAGTGAACGCCGCCTTGAGACGACCCAACGGCGCTTTGGCCGGCATTGATGAGCATG',
             'GCTTGTGATGAGGATATAACTGACTCTAATTATATTGGTTCTTTCTTAACAGACTAAGGCTCCTAGATTGCTCATACAACGGCCTAGTTTTTTTC',
             'GGCTCTTACCTCATGTGTAGTGACGAAGCTGGGCTTCCGAGTTCGTATAATCGTAAGCTCAAGTCTCCCTCTGCGTTACCTTTATGGATAGGCTG',
             'GCCGATAGTTCCTGTACTTTCGGGGTAAGTGATCCTGAGGGATCAAGCACGCAAGCCTGTGTATGGCCTGCCGCCAACCTGACATTTAATTCAGT',
             'AACTACGAGGGTTGGGTCCTGGGCCCCTTAGTCCCAAGACTGTTCATTCCCGAAACGCACTCGGTGGGTACGGCCAAACCCTAACAGCCGGATGA',
             'CTGGCGATCTATCCGCTACTAAGCCCCTTGGGAATCCCAAGGTAAGCCGTATGTACCGCCATCCTGGCGGGGGTTCGAGGTCTCCTCTTCTTGAG',
             'TGTCAGGCAGCCCACTAGGGATAGCGAGTTGTATCGTCTCCACACGCATTTACCTTGTAAACGTGGACCGGGAGTTCGTAGGGCTTCCGTTTGTG',
             'TGGATGATTGCAGGTTGAAGACTATCTGGCGGTCAGAGCTTCAGACGGACTGACCAAAGGGTTCTACGCACATAAACGGCCGACATCGGAGTATC',
             'GCAGGCTTGAATGTTATCATCCCCCTCCGTCGAGCCATTAATCCCGCCCGCGAGAAAATATTGGCTGGTCCTGAAATAGTGTGCCGGTGTGAAGA',
             'CGTGCAGCGGGCGCTATGTCGATTATAAAACATACTCTTTGAGTTTAGTGTACGAGGGCGCACTTCCAAGGCCGGCGCTGATGTCAAGGCCCCTC',
             'ATTGCCTTTAGACAGAATCCCACCCCCGAAAATAGATCACAAGCGTACGAGCACAAGATCGTGCTACGTTTGCTATAGTTCCGGTCCCACCGAGT',
             'ATTGCTAACAAAGCAGCCCCAGGGCTGTCGGAGAGTGCAGGCGTGGGCAGTATGTAGTCCTACGGAGATTGCTTTATTGTCACACTCTATTTTTG',
             'TACGTATCGTACGTGTCCTGTTTTAAAAGGTCCAAGAAGCTGGTGACGATGTCGTTGATAGGCAGTGGCAGGCGTCACCAAGCGTGGCGCATTCG',
             'TCAAAGTCCTCCGGCAGTCGGATTTAGCCCACGCCCAGGACTTCGGGAATAGGCAGGTGAGGTGAGAGCCAGGCCTGTAACCCCAAGGCGTCTTT',
             'GCGCTGGAGCCATCCGCCCCAAGGCTGCATCTGTTTGTGTCCACACAACATTAGAACTGTTATAGCGATGCGAAGTAACTGGCACGTCGAACCTA',
             'GTCGCCGTATCTCCGTGGCGAGATATGGTTCGAAGGGGCAAAGGTCGGGGGAGATTGGAGGTGGGGAAGGGAGTCCTAATCCATGTTCGTGGGAA',
             'TCATAACGAACACAGCTGCGACAAAAGCGATACTAGCACTAGGCCTCTGTCGGTCTCTGCTTTGGGGATGGGCTTCTTCAATTTTATACCGATGC',
             'AGTCCGGATATTCAGGGCCTGAGACACGCAGTCACACCACTGTGAAGACTACCACGAGAAGCTAGCCGCTATCTATCCTGCAGACTGGGTGAGCA',
             'GCGTTAAATTTGTCCCCGGACACCCTCAAGGGCCCGACGGATCTTTTTAAGTTAACGTCAACCGGGGGACATGGCTTACTATCCACAGGGATAAC',
             'ATCCTATCTATTGTGGACTCACTTAAGAAGCAGATGGCGGCGAGGAGCCGCTGGGATACACAGTTCAGTATTCACTGCGGTGAACACTAAAGCAA',
             'GGTAAATAACTATAGTCTCCTGTCTCGAACTCGTGAAGAACTGTTGCTCGAACCTAAACATCTCGTCGTACGTTCACCCTGTGTACGGAAGGGTG',
             'TCTTGAAAGCATAAGTAGACGCGCCCCCAGGGCTGACAGATCGTCCTGGTGCTGAGCATCTGAAGTCATTGTTCAAGAGGCTCTACCGGGCACGG',
             'AGATTATAACACCTATCTATCGCCTGCAAGGGCGCCGGACGGCGGCAGTATAATTATCGTAGCCCATTATAAGAGGTCCCGTAAAGTTGTCGTTC',
             'CGTATGATCGCAGTACATCCCTTATACATCTAGCAACTTGTAATCACTTCTCACTATCAGGAACTGACTGGGAGTCGAATTTGCAAATTACTGAC',
             'TCTTTGGTGATGCGTGGATTTTTCGTGATTACACGAAGCTCAAAGGACATACCACGCTCAGTTCCGCCACGCTTTGGGTTCCGGTCTAACTCCCA',
             'TTATCGTCCGAAAGGCTAGAACTCAATTAATAGGCGAAGATCACAAACCTTTCGTCGCGCGAGTGACTGGGAGGACACTCGAGCCCTGGATCCAG',
             'GTTCCCGAGCTCCTCCTACAGGCTGCCGACCGGTTAAAGGCTGGAAGAAGGTGTCAAAGTTCAGCGACCATGCAATGGTTCAACCCCACGTTCCC']

            ))