"""
@BY: Reem Alghamdi
@DATE: 17-11-2020
"""
from ch9.code.ch9_06 import suffix_array
import numpy as np


def cyclic_rotations(string):
    rotations = np.zeros((len(string), len(string)), dtype=str)
    rotations[0, :] = np.array(list(string))
    for i in range(1, len(string)):
        rotations[i, 0] = rotations[i - 1, -1]
        rotations[i, 1:] = rotations[i - 1, :-1]

    return rotations


def burrows_wheeler_transform_construction(string):
    rotations = cyclic_rotations(string)
    # print(rotations)
    return ''.join([string[x] for x in np.lexsort(rotations)])


if __name__ == "__main__":
    string = "panamabananas$"
    # string = "GCGTGCCTGGTCA$"
    # string = "AGTGGCAAAACGGTGTACCCTCACCGTCTTCCGACTCACTGTCCGCCCAAACGCAAGAGAACACAGGACGTTGCCTCACTCGACTTGTTCAGGAAATTAAGATCTAGTTCGTCTATTAGTGGATCAGATTACATCGTATTTTGGTCTCCTCATCTGATCGTTAACGCTTCCTCACCTCATTTACTCAGACGACTAGCGACCGACTCACAGGTGTAACCAATCGGGCCAGAAGAAGAGATAGGAGTTGAATGCCTGGGGCTCCCTCTAGATCATAAAGGGGCCACGCTTACGCGGGGCAGATTTTGAGCAAAGGGCCCCAGCGGAGGTGCCAAATGGTTTTCGATGCTGAGATCCGCTCCCATACTACCTATTACGGTCGGATGAGGTATAGTCTAGGTTAGTGTCTCTGGGAAATTGATTAATGTACGTTTACGGCCGCCTCGTTTAACGCATAACTTATAGGGCGCTTTTTCAAGCCTACTGATGAATTCCAGTTGGGTAACGAGTTTGCACACGCGCTACGCCGTAACAACCTACGAGCTCCTATAGTTAGGCCAACCATATCAGGCTATAGCCACAGACAGGAACAAACTAATGATTCGGGCATCGAGCCTAGCTGTGTCATCCATTGTATTCTTTACTCAGAGCGAGATTGGCTCGTAATCTTCTCAGGGGAGCCTCAGACAGTTAATGTTTCTAGAGTCCCCTCCATCTCGCACCTGGCCGTTTCGTATGTCGCCATCTGTGTTACCTGGGTAATTCCCTTGATCCTTGTTTCTCATATGGAGCTTTTGCATATGGGCTTAACCGTAAGCCCATTAACGGAGCTTGCGTCCGCGCTGGAGCATAAGTGCACTAAAGAACAGCGCAGATCATTG$"
    # string = "GTCCCCGTTCTCCGATACAGTCTTTGGTCGGGATGAGCGAATCATTTGAAACTACTACTTACGTCCGTTGATGACTTGGCCGCAAATTAAGAGAAATGCTTGATCGACGTGCAAGCGATACTTAGGTGCCGTGGTACATCATGATTGCACTTTCCAAGTCTAGTTTAGGCGAACGGTCGGCGGTACGCCTTCAATCGTGCCCTGTCGAAGGGATCATTGGGAGGCAAGGGCTCTAGCATGTGCTATAGTGAGTACGAGTCGGCACCAGAATCATGTTCGCCGGCGTTACACGACCAACTCGGATTTTAAGTCGACGCTTAAGGATCGGAGTAGCCCGGCACAAACAACATAGCAACTCTGTAGAAATGCCTAGAGCAGGTCATGGTTTACTTGGGCTATAATGATTTAAGCTATTACATCCTTAGCGTAGTGGCGTTTTTCCTTCGGGTTCTATCGACTCATCGTGATATCGGGACGCCCTAAAGCGTAGTAGGCGGGAGTCACTTGGGCAGCGACTTCTACGTCTGCGTCCTCTGACTTGGTTACGACTGGGAAGACCCTATTGCATGGAGTAAACCCGTTCGAGAGGCATTTAGTATAATTCCGAGCAGATGTTAAACCATCGGCCGCTGGCACCACATTGGACCAGTGGCGTCTGTACTCCGCCTAATATGCAGCCATCTACAATATCCAAAATAGCGTAAGCACATTATAAACCTATATGGCCCGGACCCTCTTCCGCAAGGCCCGGAGGGCGCTACTCAGACACTGGCAGCTTTACCGCCACATTACGCAGTGTGATGTAAGAGGTACCACGCTCGTAGCTTTAAGTTCACGACAGATCCACCCTACAGCGAGCACTACACTGCCAAGCCCCATACATCCGAAAACCCTACCACCGCAAGCCGGCTGCTCAGTTCGACGCGTCAAGGACTAAAGAGACCGTATACGAGTTCTAGTAATCTTGCCTCTGTACACTGCAACA$"
    print(burrows_wheeler_transform_construction(string))
