"""
@BY: Reem Alghamdi
@DATE: 18-11-2020
"""


def inverse_burrows_wheeler_transform(text):
    len_txt = len(text)
    last_col = [(text[i], i) for i in range(len_txt)]
    first_col = sorted(last_col)
    original = [first_col[0]]
    for i in range(len_txt):
        original.append(first_col[last_col.index(original[i])])

    return ''.join(x[0] for x in original[1:])


if __name__ == "__main__":
    # print(inverse_burrows_wheeler_transform("ard$rcaaaabb"))
    # print(inverse_burrows_wheeler_transform("TTCCTAACG$A"))
    # print(inverse_burrows_wheeler_transform("enwvpeoseu$llt"))
    print(inverse_burrows_wheeler_transform("CTTCGCTCCCATCGCACTACGGTCTACGCAAAAGACTCGGGCCGGACCGCCTTATACGCTTATGGCCCGTTCTGACAGGCCTGTTAGGGGAGTCGAAGATCTAAAAAGTTCGCGCTAGATAGCCCTCACCCGTACCTTCGTTGAGTAGGACCTCCGCATAGCGTTAGCAGTGACAAAGGTCATCGCTAGGCTCGCGTGGTAGCTCCCCCGCATATGCGATGGTAGCGCCGTGAGACATAATTACCACGAAACTCGAGGTATCTCAGCGTCCGCCCGGGGCTAAGGCGGAGGGTCACCGTTCCAGAGTAGGGTTTGCATCGCCAAAAACGGAATAGGGTATAGCTATCACTGATGTCCAGGTCTCAAAGGTTACATACCGCGTCCGAGAACCTCGAGTTCTAAAAGAGCGTCACCCACAAATATTTTAACATGTGCGCGGGGATCATTAAAACGGGGCCTAGTGCGCTTCGCCATATTGGGATGCATTTGGTCGACAATAGCTAGTTTGGGCGGCATAAATTGAAGTGTAGTAATTTCTGCCCGGCGGTTACCAGGCACAAATCAGCCTCAGGCGCAGTAAGTTTAGATAATAACAATGCAGCTACGTCGACGCCTGAGGACAACAAATTTGATCCACGGGGAACACTCGGTCAGAGGTCTCCCAGGAGCGGGAGAACTATACTCTCCGCCGAGGACCCATTTGTAACCTAAGAAGGCTTAAGCCATTCGAGGTTCCTTGAAGGGGATTTTCTGCTTCCATTGACATAGACCGAAAGTTACGCGTTTCCTTTCCCGCAACTGGACGCTCAACGAACGAGAACGGCGACTAGGCAGTTCGCTAGATTTCGAACGGCGTGTGGAAACAGTTCCCCGATGACACGATAACTCACCTGTTTTCGGACCGA$"))