"""
@BY: Reem Alghamdi
@DATE: 17-09-2020
"""


def de_bruijn_graph(text, k):
    """
    :param text: the string
    :param k: length of k-mer
    :return adjacency list of prefix/suffix
    """
    edges = [text[i:i+k] for i in range(len(text) - k + 1)]
    adj_list = {}
    for edge in edges:
        from_prefix = edge[:-1]
        to_suffix = edge[1:]
        if adj_list.get(from_prefix):
            adj_list[from_prefix].append(to_suffix)
        else:
            adj_list[from_prefix] = [to_suffix]
    return adj_list


if __name__ == "__main__":
    for node, lists in de_bruijn_graph("TGTGCCTGAGGAGTTCCCTTACCGAAAGACCTATTTAGGATCTCTCGATCGTCTAACAGGCTTTTCAGCGGCCAGAACGCGTTCTGGGGCAGCCGCTTGAGTACCCTAACAGCGAAAGCATGGACAAGCTTTCTCACCGCACGTAGACGTTGGAAAGTACGCCATCCAGTCCCGGATGGTGGTCTATAAGCATTGCACTTAAGACCGTATAATTGTCGCTGTGGATTTAGCAAGCGCCCCGCTAAACAGTCAGTGCGAAGGGTGAGGCCTTTGTAGTCTGGGTTCTAAAGACTTCAACAGGCTGGAGTCCTCGGGAGTTGACGCTTCAGACGACTATTATTCTGATGCACAAATGGCCCCAAAGCTGCGCTCGCCAACCAGCCTCCAGTAGGGACCGTATAATCTGGTATGCGGTGTAAGCTCCAGGAAGGGGCGCATCAAGAGCTTGTAGCATATAGCGCCCCGTCGTTCAAAATGCTAGACGTAGGATCCTCTACACTGATTTATTTAGGGCGCCTACTCGGTTGGTTCCTGCTGGCGTGCGTGCACCGTAGGATACCCTTCGCTACCGTGTGCCTCTAAAGCGGCTGGTAAGGGTGCGAACAATACACGCACTTTTCGATCCCAAAAAGTTAGCCGGCCAAGAAGTAGCCGACCAGTGAATTCCTATAGTGTGTTTGTACGAGGGCCCTCAAGTGGTCATATAAATGCGTCGCTATAGCTTAGCTATGGCCGTTCCGCCCATGCTAGGGAAACGCAATACAGGCTTTGCCCGCCTTCTGAATGAGTCCTCGGACCTGGCTCCCCCCGTTGTTTTTAGTCCTTTTATAAGCTCGATAGGGTTAATCGATCTAAAGAGGAAGACATAGTCGCTTCATACTCTCCCATTGACTCAGTAGGATTCTCAAGCAAGGCTGCAAGTTGCTACAAATATGTTCTCAAGCTCTTGATCCCGCGAGAGTACGAATCGAGACGAATATCACGGTTGCCGAGGACCTCCGCCCTCTAGCAATCGCCAACGCGGACCGTGATGGCGGTGACTTGACGCCAGTGTGAAAGTGTGGTTCGCCACATGAAACTAAGCAATATCCACACTTTAGCCTTAGCTAAGCGCTGGTTATTTCAGGCCCCGCTCAATAAGGGGTAACAGCGCTGTGTGGACGTCTCAACACTGACGCCCTTACTGTGTCAGAGGTATGCCATCCAGAGAGAAGAGTCCAGAAGTCTAGTCCACCTAGTAGTCCAGCAAGTTCCCTGTCAGGACGGGGCTCGACCCGTTAGAGAGGGCCAAAAGCCATCTGCCTTGCGCGAGCGCCACGTGCGAGTAATGGTGAGTTCTTAGGCAACCCATTACCCTTCTGTACCTGCTGTATTGCGCTATATACTGCATCCCGGTCAAGGGTGGAGAAGCCCCGAATAATTTCTATGGATTGCAGATCAGTCGGCTGGAGCCCCACGTTCATTAATATTCCGCAACTAGTCTCGCTGCCGCCACCATATCATCACTGCAGTGTAGCGGCTGCGTTGGCAGGGGATCAGTAGCGCACGCTTGATCGAACAATTACTCTGAATGTGTTAAACTCATGGTTATAGTAACCTATCACACGCAGGGCGTGAAATTTGACCGTGGACTCGGTGCCCCAAGATGAAGCCAGATGCATTATCATAGATCCGTTGTCCGTATCAGGGTTCTTAAATTGGGGGTACCCCTGGCCCTGCCGAATGGTCTAACGTCCTATCGTATGGGGCCCTTCATCTAAAGCCTTGTAGTACTGTGCAGCGTATGACGTATGAGCCTCTACCTATGGATGGAAGTATCGCGGCGGTCAGTCTAACTCGCCTGTATAAATTCACCAGTTATCAGTGGATAATGGGATGGCGACCGCGGAACTAAAGAAACGCAGCATTCCCATGTGGGCTGATCTCTAACTATTACTATATGCCGACAACCAGATATACACACCACGGAAGATTAGAAATACCATTAGCCACAGTGATCG", 12).items():
        print(node, " -> ", ', '.join(lists))

